//
//  Copyright (C) 2021 7Cav.us
//  This file is part of 7Cav-API <https://github.com/7cav/api>.
//
//  7Cav-API is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  7Cav-API is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with 7Cav-API. If not, see <http://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: milpacs.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MilpacService_GetProfile_FullMethodName           = "/proto.MilpacService/GetProfile"
	MilpacService_GetRoster_FullMethodName            = "/proto.MilpacService/GetRoster"
	MilpacService_GetUserViaKeycloakId_FullMethodName = "/proto.MilpacService/GetUserViaKeycloakId"
	MilpacService_GetUserViaDiscordId_FullMethodName  = "/proto.MilpacService/GetUserViaDiscordId"
	MilpacService_GetLiteRoster_FullMethodName        = "/proto.MilpacService/GetLiteRoster"
	MilpacService_SearchByPosition_FullMethodName     = "/proto.MilpacService/SearchByPosition"
	MilpacService_GetS1UniformsRoster_FullMethodName  = "/proto.MilpacService/GetS1UniformsRoster"
)

// MilpacServiceClient is the client API for MilpacService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MilpacServiceClient interface {
	GetProfile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*Profile, error)
	GetRoster(ctx context.Context, in *RosterRequest, opts ...grpc.CallOption) (*Roster, error)
	GetUserViaKeycloakId(ctx context.Context, in *KeycloakIdRequest, opts ...grpc.CallOption) (*Profile, error)
	GetUserViaDiscordId(ctx context.Context, in *DiscordIdRequest, opts ...grpc.CallOption) (*Profile, error)
	GetLiteRoster(ctx context.Context, in *RosterRequest, opts ...grpc.CallOption) (*LiteRoster, error)
	SearchByPosition(ctx context.Context, in *PositionSearchRequest, opts ...grpc.CallOption) (*LiteRoster, error)
	GetS1UniformsRoster(ctx context.Context, in *RosterRequest, opts ...grpc.CallOption) (*S1UniformsRoster, error)
}

type milpacServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMilpacServiceClient(cc grpc.ClientConnInterface) MilpacServiceClient {
	return &milpacServiceClient{cc}
}

func (c *milpacServiceClient) GetProfile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*Profile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Profile)
	err := c.cc.Invoke(ctx, MilpacService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *milpacServiceClient) GetRoster(ctx context.Context, in *RosterRequest, opts ...grpc.CallOption) (*Roster, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Roster)
	err := c.cc.Invoke(ctx, MilpacService_GetRoster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *milpacServiceClient) GetUserViaKeycloakId(ctx context.Context, in *KeycloakIdRequest, opts ...grpc.CallOption) (*Profile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Profile)
	err := c.cc.Invoke(ctx, MilpacService_GetUserViaKeycloakId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *milpacServiceClient) GetUserViaDiscordId(ctx context.Context, in *DiscordIdRequest, opts ...grpc.CallOption) (*Profile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Profile)
	err := c.cc.Invoke(ctx, MilpacService_GetUserViaDiscordId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *milpacServiceClient) GetLiteRoster(ctx context.Context, in *RosterRequest, opts ...grpc.CallOption) (*LiteRoster, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LiteRoster)
	err := c.cc.Invoke(ctx, MilpacService_GetLiteRoster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *milpacServiceClient) SearchByPosition(ctx context.Context, in *PositionSearchRequest, opts ...grpc.CallOption) (*LiteRoster, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LiteRoster)
	err := c.cc.Invoke(ctx, MilpacService_SearchByPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *milpacServiceClient) GetS1UniformsRoster(ctx context.Context, in *RosterRequest, opts ...grpc.CallOption) (*S1UniformsRoster, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(S1UniformsRoster)
	err := c.cc.Invoke(ctx, MilpacService_GetS1UniformsRoster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MilpacServiceServer is the server API for MilpacService service.
// All implementations should embed UnimplementedMilpacServiceServer
// for forward compatibility.
type MilpacServiceServer interface {
	GetProfile(context.Context, *ProfileRequest) (*Profile, error)
	GetRoster(context.Context, *RosterRequest) (*Roster, error)
	GetUserViaKeycloakId(context.Context, *KeycloakIdRequest) (*Profile, error)
	GetUserViaDiscordId(context.Context, *DiscordIdRequest) (*Profile, error)
	GetLiteRoster(context.Context, *RosterRequest) (*LiteRoster, error)
	SearchByPosition(context.Context, *PositionSearchRequest) (*LiteRoster, error)
	GetS1UniformsRoster(context.Context, *RosterRequest) (*S1UniformsRoster, error)
}

// UnimplementedMilpacServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMilpacServiceServer struct{}

func (UnimplementedMilpacServiceServer) GetProfile(context.Context, *ProfileRequest) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedMilpacServiceServer) GetRoster(context.Context, *RosterRequest) (*Roster, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoster not implemented")
}
func (UnimplementedMilpacServiceServer) GetUserViaKeycloakId(context.Context, *KeycloakIdRequest) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserViaKeycloakId not implemented")
}
func (UnimplementedMilpacServiceServer) GetUserViaDiscordId(context.Context, *DiscordIdRequest) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserViaDiscordId not implemented")
}
func (UnimplementedMilpacServiceServer) GetLiteRoster(context.Context, *RosterRequest) (*LiteRoster, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLiteRoster not implemented")
}
func (UnimplementedMilpacServiceServer) SearchByPosition(context.Context, *PositionSearchRequest) (*LiteRoster, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchByPosition not implemented")
}
func (UnimplementedMilpacServiceServer) GetS1UniformsRoster(context.Context, *RosterRequest) (*S1UniformsRoster, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetS1UniformsRoster not implemented")
}
func (UnimplementedMilpacServiceServer) testEmbeddedByValue() {}

// UnsafeMilpacServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MilpacServiceServer will
// result in compilation errors.
type UnsafeMilpacServiceServer interface {
	mustEmbedUnimplementedMilpacServiceServer()
}

func RegisterMilpacServiceServer(s grpc.ServiceRegistrar, srv MilpacServiceServer) {
	// If the following call pancis, it indicates UnimplementedMilpacServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MilpacService_ServiceDesc, srv)
}

func _MilpacService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MilpacServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MilpacService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MilpacServiceServer).GetProfile(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MilpacService_GetRoster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RosterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MilpacServiceServer).GetRoster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MilpacService_GetRoster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MilpacServiceServer).GetRoster(ctx, req.(*RosterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MilpacService_GetUserViaKeycloakId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeycloakIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MilpacServiceServer).GetUserViaKeycloakId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MilpacService_GetUserViaKeycloakId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MilpacServiceServer).GetUserViaKeycloakId(ctx, req.(*KeycloakIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MilpacService_GetUserViaDiscordId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscordIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MilpacServiceServer).GetUserViaDiscordId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MilpacService_GetUserViaDiscordId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MilpacServiceServer).GetUserViaDiscordId(ctx, req.(*DiscordIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MilpacService_GetLiteRoster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RosterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MilpacServiceServer).GetLiteRoster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MilpacService_GetLiteRoster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MilpacServiceServer).GetLiteRoster(ctx, req.(*RosterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MilpacService_SearchByPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PositionSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MilpacServiceServer).SearchByPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MilpacService_SearchByPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MilpacServiceServer).SearchByPosition(ctx, req.(*PositionSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MilpacService_GetS1UniformsRoster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RosterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MilpacServiceServer).GetS1UniformsRoster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MilpacService_GetS1UniformsRoster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MilpacServiceServer).GetS1UniformsRoster(ctx, req.(*RosterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MilpacService_ServiceDesc is the grpc.ServiceDesc for MilpacService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MilpacService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MilpacService",
	HandlerType: (*MilpacServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProfile",
			Handler:    _MilpacService_GetProfile_Handler,
		},
		{
			MethodName: "GetRoster",
			Handler:    _MilpacService_GetRoster_Handler,
		},
		{
			MethodName: "GetUserViaKeycloakId",
			Handler:    _MilpacService_GetUserViaKeycloakId_Handler,
		},
		{
			MethodName: "GetUserViaDiscordId",
			Handler:    _MilpacService_GetUserViaDiscordId_Handler,
		},
		{
			MethodName: "GetLiteRoster",
			Handler:    _MilpacService_GetLiteRoster_Handler,
		},
		{
			MethodName: "SearchByPosition",
			Handler:    _MilpacService_SearchByPosition_Handler,
		},
		{
			MethodName: "GetS1UniformsRoster",
			Handler:    _MilpacService_GetS1UniformsRoster_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "milpacs.proto",
}
