//
//  Copyright (C) 2021 7Cav.us
//  This file is part of 7Cav-API <https://github.com/7cav/api>.
//
//  7Cav-API is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  7Cav-API is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with 7Cav-API. If not, see <http://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: milpacs.proto

package proto

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RosterType int32

const (
	RosterType_ROSTER_TYPE_UNSPECIFIED   RosterType = 0
	RosterType_ROSTER_TYPE_COMBAT        RosterType = 1
	RosterType_ROSTER_TYPE_RESERVE       RosterType = 2
	RosterType_ROSTER_TYPE_ELOA          RosterType = 3
	RosterType_ROSTER_TYPE_WALL_OF_HONOR RosterType = 4
	RosterType_ROSTER_TYPE_ARLINGTON     RosterType = 5
	RosterType_ROSTER_TYPE_PAST_MEMBERS  RosterType = 6
)

// Enum value maps for RosterType.
var (
	RosterType_name = map[int32]string{
		0: "ROSTER_TYPE_UNSPECIFIED",
		1: "ROSTER_TYPE_COMBAT",
		2: "ROSTER_TYPE_RESERVE",
		3: "ROSTER_TYPE_ELOA",
		4: "ROSTER_TYPE_WALL_OF_HONOR",
		5: "ROSTER_TYPE_ARLINGTON",
		6: "ROSTER_TYPE_PAST_MEMBERS",
	}
	RosterType_value = map[string]int32{
		"ROSTER_TYPE_UNSPECIFIED":   0,
		"ROSTER_TYPE_COMBAT":        1,
		"ROSTER_TYPE_RESERVE":       2,
		"ROSTER_TYPE_ELOA":          3,
		"ROSTER_TYPE_WALL_OF_HONOR": 4,
		"ROSTER_TYPE_ARLINGTON":     5,
		"ROSTER_TYPE_PAST_MEMBERS":  6,
	}
)

func (x RosterType) Enum() *RosterType {
	p := new(RosterType)
	*p = x
	return p
}

func (x RosterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RosterType) Descriptor() protoreflect.EnumDescriptor {
	return file_milpacs_proto_enumTypes[0].Descriptor()
}

func (RosterType) Type() protoreflect.EnumType {
	return &file_milpacs_proto_enumTypes[0]
}

func (x RosterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RosterType.Descriptor instead.
func (RosterType) EnumDescriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{0}
}

type RecordType int32

const (
	RecordType_RECORD_TYPE_UNSPECIFIED  RecordType = 0
	RecordType_RECORD_TYPE_PROMOTION    RecordType = 1
	RecordType_RECORD_TYPE_OPERATION    RecordType = 2
	RecordType_RECORD_TYPE_TRANSFER     RecordType = 3
	RecordType_RECORD_TYPE_DISCIPLINARY RecordType = 4
	RecordType_RECORD_TYPE_DISCHARGE    RecordType = 5
	RecordType_RECORD_TYPE_ASSIGNMENT   RecordType = 6
	RecordType_RECORD_TYPE_NAME_CHANGE  RecordType = 7
	RecordType_RECORD_TYPE_ELOA         RecordType = 8
	RecordType_RECORD_TYPE_GRADUATION   RecordType = 9
)

// Enum value maps for RecordType.
var (
	RecordType_name = map[int32]string{
		0: "RECORD_TYPE_UNSPECIFIED",
		1: "RECORD_TYPE_PROMOTION",
		2: "RECORD_TYPE_OPERATION",
		3: "RECORD_TYPE_TRANSFER",
		4: "RECORD_TYPE_DISCIPLINARY",
		5: "RECORD_TYPE_DISCHARGE",
		6: "RECORD_TYPE_ASSIGNMENT",
		7: "RECORD_TYPE_NAME_CHANGE",
		8: "RECORD_TYPE_ELOA",
		9: "RECORD_TYPE_GRADUATION",
	}
	RecordType_value = map[string]int32{
		"RECORD_TYPE_UNSPECIFIED":  0,
		"RECORD_TYPE_PROMOTION":    1,
		"RECORD_TYPE_OPERATION":    2,
		"RECORD_TYPE_TRANSFER":     3,
		"RECORD_TYPE_DISCIPLINARY": 4,
		"RECORD_TYPE_DISCHARGE":    5,
		"RECORD_TYPE_ASSIGNMENT":   6,
		"RECORD_TYPE_NAME_CHANGE":  7,
		"RECORD_TYPE_ELOA":         8,
		"RECORD_TYPE_GRADUATION":   9,
	}
)

func (x RecordType) Enum() *RecordType {
	p := new(RecordType)
	*p = x
	return p
}

func (x RecordType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecordType) Descriptor() protoreflect.EnumDescriptor {
	return file_milpacs_proto_enumTypes[1].Descriptor()
}

func (RecordType) Type() protoreflect.EnumType {
	return &file_milpacs_proto_enumTypes[1]
}

func (x RecordType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecordType.Descriptor instead.
func (RecordType) EnumDescriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{1}
}

type RankType int32

const (
	RankType_RANK_TYPE_UNSPECIFIED RankType = 0
	RankType_RANK_TYPE_GOA         RankType = 1
	RankType_RANK_TYPE_GEN         RankType = 2
	RankType_RANK_TYPE_LTG         RankType = 3
	RankType_RANK_TYPE_MG          RankType = 4
	RankType_RANK_TYPE_BG          RankType = 5
	RankType_RANK_TYPE_COL         RankType = 6
	RankType_RANK_TYPE_LTC         RankType = 7
	RankType_RANK_TYPE_MAJ         RankType = 8
	RankType_RANK_TYPE_CPT         RankType = 9
	RankType_RANK_TYPE_1LT         RankType = 10
	RankType_RANK_TYPE_2LT         RankType = 11
	RankType_RANK_TYPE_CSM         RankType = 12
	RankType_RANK_TYPE_SGM         RankType = 13
	RankType_RANK_TYPE_1SG         RankType = 14
	RankType_RANK_TYPE_MSG         RankType = 15
	RankType_RANK_TYPE_SFC         RankType = 16
	RankType_RANK_TYPE_SSG         RankType = 17
	RankType_RANK_TYPE_SGT         RankType = 18
	RankType_RANK_TYPE_CPL         RankType = 19
	RankType_RANK_TYPE_SPC         RankType = 20
	RankType_RANK_TYPE_PFC         RankType = 21
	RankType_RANK_TYPE_PVT         RankType = 22
	RankType_RANK_TYPE_RCT         RankType = 23
	RankType_RANK_TYPE_CW5         RankType = 26
	RankType_RANK_TYPE_CW4         RankType = 27
	RankType_RANK_TYPE_CW3         RankType = 28
	RankType_RANK_TYPE_CW2         RankType = 29
	RankType_RANK_TYPE_WO1         RankType = 30
	RankType_RANK_TYPE_AR          RankType = 31
)

// Enum value maps for RankType.
var (
	RankType_name = map[int32]string{
		0:  "RANK_TYPE_UNSPECIFIED",
		1:  "RANK_TYPE_GOA",
		2:  "RANK_TYPE_GEN",
		3:  "RANK_TYPE_LTG",
		4:  "RANK_TYPE_MG",
		5:  "RANK_TYPE_BG",
		6:  "RANK_TYPE_COL",
		7:  "RANK_TYPE_LTC",
		8:  "RANK_TYPE_MAJ",
		9:  "RANK_TYPE_CPT",
		10: "RANK_TYPE_1LT",
		11: "RANK_TYPE_2LT",
		12: "RANK_TYPE_CSM",
		13: "RANK_TYPE_SGM",
		14: "RANK_TYPE_1SG",
		15: "RANK_TYPE_MSG",
		16: "RANK_TYPE_SFC",
		17: "RANK_TYPE_SSG",
		18: "RANK_TYPE_SGT",
		19: "RANK_TYPE_CPL",
		20: "RANK_TYPE_SPC",
		21: "RANK_TYPE_PFC",
		22: "RANK_TYPE_PVT",
		23: "RANK_TYPE_RCT",
		26: "RANK_TYPE_CW5",
		27: "RANK_TYPE_CW4",
		28: "RANK_TYPE_CW3",
		29: "RANK_TYPE_CW2",
		30: "RANK_TYPE_WO1",
		31: "RANK_TYPE_AR",
	}
	RankType_value = map[string]int32{
		"RANK_TYPE_UNSPECIFIED": 0,
		"RANK_TYPE_GOA":         1,
		"RANK_TYPE_GEN":         2,
		"RANK_TYPE_LTG":         3,
		"RANK_TYPE_MG":          4,
		"RANK_TYPE_BG":          5,
		"RANK_TYPE_COL":         6,
		"RANK_TYPE_LTC":         7,
		"RANK_TYPE_MAJ":         8,
		"RANK_TYPE_CPT":         9,
		"RANK_TYPE_1LT":         10,
		"RANK_TYPE_2LT":         11,
		"RANK_TYPE_CSM":         12,
		"RANK_TYPE_SGM":         13,
		"RANK_TYPE_1SG":         14,
		"RANK_TYPE_MSG":         15,
		"RANK_TYPE_SFC":         16,
		"RANK_TYPE_SSG":         17,
		"RANK_TYPE_SGT":         18,
		"RANK_TYPE_CPL":         19,
		"RANK_TYPE_SPC":         20,
		"RANK_TYPE_PFC":         21,
		"RANK_TYPE_PVT":         22,
		"RANK_TYPE_RCT":         23,
		"RANK_TYPE_CW5":         26,
		"RANK_TYPE_CW4":         27,
		"RANK_TYPE_CW3":         28,
		"RANK_TYPE_CW2":         29,
		"RANK_TYPE_WO1":         30,
		"RANK_TYPE_AR":          31,
	}
)

func (x RankType) Enum() *RankType {
	p := new(RankType)
	*p = x
	return p
}

func (x RankType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RankType) Descriptor() protoreflect.EnumDescriptor {
	return file_milpacs_proto_enumTypes[2].Descriptor()
}

func (RankType) Type() protoreflect.EnumType {
	return &file_milpacs_proto_enumTypes[2]
}

func (x RankType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RankType.Descriptor instead.
func (RankType) EnumDescriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{2}
}

type ProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileRequest) Reset() {
	*x = ProfileRequest{}
	mi := &file_milpacs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileRequest) ProtoMessage() {}

func (x *ProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_milpacs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileRequest.ProtoReflect.Descriptor instead.
func (*ProfileRequest) Descriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{0}
}

func (x *ProfileRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ProfileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type KeycloakIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeycloakId    string                 `protobuf:"bytes,1,opt,name=keycloak_id,json=keycloakId,proto3" json:"keycloak_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeycloakIdRequest) Reset() {
	*x = KeycloakIdRequest{}
	mi := &file_milpacs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeycloakIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeycloakIdRequest) ProtoMessage() {}

func (x *KeycloakIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_milpacs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeycloakIdRequest.ProtoReflect.Descriptor instead.
func (*KeycloakIdRequest) Descriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{1}
}

func (x *KeycloakIdRequest) GetKeycloakId() string {
	if x != nil {
		return x.KeycloakId
	}
	return ""
}

type DiscordIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiscordId     string                 `protobuf:"bytes,1,opt,name=discord_id,json=discordId,proto3" json:"discord_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscordIdRequest) Reset() {
	*x = DiscordIdRequest{}
	mi := &file_milpacs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscordIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscordIdRequest) ProtoMessage() {}

func (x *DiscordIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_milpacs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscordIdRequest.ProtoReflect.Descriptor instead.
func (*DiscordIdRequest) Descriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{2}
}

func (x *DiscordIdRequest) GetDiscordId() string {
	if x != nil {
		return x.DiscordId
	}
	return ""
}

type Rank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RankShort     string                 `protobuf:"bytes,1,opt,name=rank_short,json=rankShort,proto3" json:"rank_short,omitempty"`
	RankFull      string                 `protobuf:"bytes,2,opt,name=rank_full,json=rankFull,proto3" json:"rank_full,omitempty"`
	RankImageUrl  string                 `protobuf:"bytes,3,opt,name=rank_image_url,json=rankImageUrl,proto3" json:"rank_image_url,omitempty"`
	RankId        uint64                 `protobuf:"varint,4,opt,name=rank_id,json=rankId,proto3" json:"rank_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rank) Reset() {
	*x = Rank{}
	mi := &file_milpacs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rank) ProtoMessage() {}

func (x *Rank) ProtoReflect() protoreflect.Message {
	mi := &file_milpacs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rank.ProtoReflect.Descriptor instead.
func (*Rank) Descriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{3}
}

func (x *Rank) GetRankShort() string {
	if x != nil {
		return x.RankShort
	}
	return ""
}

func (x *Rank) GetRankFull() string {
	if x != nil {
		return x.RankFull
	}
	return ""
}

func (x *Rank) GetRankImageUrl() string {
	if x != nil {
		return x.RankImageUrl
	}
	return ""
}

func (x *Rank) GetRankId() uint64 {
	if x != nil {
		return x.RankId
	}
	return 0
}

type Thingy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           string                 `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Thingy) Reset() {
	*x = Thingy{}
	mi := &file_milpacs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Thingy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thingy) ProtoMessage() {}

func (x *Thingy) ProtoReflect() protoreflect.Message {
	mi := &file_milpacs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thingy.ProtoReflect.Descriptor instead.
func (*Thingy) Descriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{4}
}

func (x *Thingy) GetAck() string {
	if x != nil {
		return x.Ack
	}
	return ""
}

type Profile struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	User              *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Rank              *Rank                  `protobuf:"bytes,2,opt,name=rank,proto3" json:"rank,omitempty"`
	RealName          string                 `protobuf:"bytes,3,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	UniformUrl        string                 `protobuf:"bytes,4,opt,name=uniform_url,json=uniformUrl,proto3" json:"uniform_url,omitempty"`
	Roster            RosterType             `protobuf:"varint,5,opt,name=roster,proto3,enum=proto.RosterType" json:"roster,omitempty"`
	Primary           *Position              `protobuf:"bytes,6,opt,name=primary,proto3" json:"primary,omitempty"`
	Secondaries       []*Position            `protobuf:"bytes,7,rep,name=secondaries,proto3" json:"secondaries,omitempty"`
	Records           []*Record              `protobuf:"bytes,8,rep,name=records,proto3" json:"records,omitempty"`
	Awards            []*Award               `protobuf:"bytes,9,rep,name=awards,proto3" json:"awards,omitempty"`
	JoinDate          string                 `protobuf:"bytes,10,opt,name=join_date,json=joinDate,proto3" json:"join_date,omitempty"`
	PromotionDate     string                 `protobuf:"bytes,11,opt,name=promotion_date,json=promotionDate,proto3" json:"promotion_date,omitempty"`
	KeycloakId        string                 `protobuf:"bytes,12,opt,name=keycloak_id,json=keycloakId,proto3" json:"keycloak_id,omitempty"`
	DiscordId         string                 `protobuf:"bytes,13,opt,name=discord_id,json=discordId,proto3" json:"discord_id,omitempty"`
	LastForumPostDate string                 `protobuf:"bytes,14,opt,name=last_forum_post_date,json=lastForumPostDate,proto3" json:"last_forum_post_date,omitempty"`
	Mos               string                 `protobuf:"bytes,15,opt,name=mos,proto3" json:"mos,omitempty"`
	ConsoleGamertag   string                 `protobuf:"bytes,16,opt,name=console_gamertag,json=consoleGamertag,proto3" json:"console_gamertag,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_milpacs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_milpacs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{5}
}

func (x *Profile) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Profile) GetRank() *Rank {
	if x != nil {
		return x.Rank
	}
	return nil
}

func (x *Profile) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *Profile) GetUniformUrl() string {
	if x != nil {
		return x.UniformUrl
	}
	return ""
}

func (x *Profile) GetRoster() RosterType {
	if x != nil {
		return x.Roster
	}
	return RosterType_ROSTER_TYPE_UNSPECIFIED
}

func (x *Profile) GetPrimary() *Position {
	if x != nil {
		return x.Primary
	}
	return nil
}

func (x *Profile) GetSecondaries() []*Position {
	if x != nil {
		return x.Secondaries
	}
	return nil
}

func (x *Profile) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *Profile) GetAwards() []*Award {
	if x != nil {
		return x.Awards
	}
	return nil
}

func (x *Profile) GetJoinDate() string {
	if x != nil {
		return x.JoinDate
	}
	return ""
}

func (x *Profile) GetPromotionDate() string {
	if x != nil {
		return x.PromotionDate
	}
	return ""
}

func (x *Profile) GetKeycloakId() string {
	if x != nil {
		return x.KeycloakId
	}
	return ""
}

func (x *Profile) GetDiscordId() string {
	if x != nil {
		return x.DiscordId
	}
	return ""
}

func (x *Profile) GetLastForumPostDate() string {
	if x != nil {
		return x.LastForumPostDate
	}
	return ""
}

func (x *Profile) GetMos() string {
	if x != nil {
		return x.Mos
	}
	return ""
}

func (x *Profile) GetConsoleGamertag() string {
	if x != nil {
		return x.ConsoleGamertag
	}
	return ""
}

type RosterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roster        RosterType             `protobuf:"varint,1,opt,name=roster,proto3,enum=proto.RosterType" json:"roster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RosterRequest) Reset() {
	*x = RosterRequest{}
	mi := &file_milpacs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RosterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RosterRequest) ProtoMessage() {}

func (x *RosterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_milpacs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RosterRequest.ProtoReflect.Descriptor instead.
func (*RosterRequest) Descriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{6}
}

func (x *RosterRequest) GetRoster() RosterType {
	if x != nil {
		return x.Roster
	}
	return RosterType_ROSTER_TYPE_UNSPECIFIED
}

type Roster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      map[uint64]*Profile    `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Roster) Reset() {
	*x = Roster{}
	mi := &file_milpacs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Roster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Roster) ProtoMessage() {}

func (x *Roster) ProtoReflect() protoreflect.Message {
	mi := &file_milpacs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Roster.ProtoReflect.Descriptor instead.
func (*Roster) Descriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{7}
}

func (x *Roster) GetProfiles() map[uint64]*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_milpacs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_milpacs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{8}
}

func (x *User) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordDetails string                 `protobuf:"bytes,1,opt,name=record_details,json=recordDetails,proto3" json:"record_details,omitempty"`
	RecordType    RecordType             `protobuf:"varint,2,opt,name=record_type,json=recordType,proto3,enum=proto.RecordType" json:"record_type,omitempty"`
	RecordDate    string                 `protobuf:"bytes,3,opt,name=record_date,json=recordDate,proto3" json:"record_date,omitempty"`
	RecordUid     uint64                 `protobuf:"varint,4,opt,name=record_uid,json=recordUid,proto3" json:"record_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_milpacs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_milpacs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{9}
}

func (x *Record) GetRecordDetails() string {
	if x != nil {
		return x.RecordDetails
	}
	return ""
}

func (x *Record) GetRecordType() RecordType {
	if x != nil {
		return x.RecordType
	}
	return RecordType_RECORD_TYPE_UNSPECIFIED
}

func (x *Record) GetRecordDate() string {
	if x != nil {
		return x.RecordDate
	}
	return ""
}

func (x *Record) GetRecordUid() uint64 {
	if x != nil {
		return x.RecordUid
	}
	return 0
}

type Award struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AwardDetails  string                 `protobuf:"bytes,1,opt,name=award_details,json=awardDetails,proto3" json:"award_details,omitempty"`
	AwardName     string                 `protobuf:"bytes,2,opt,name=award_name,json=awardName,proto3" json:"award_name,omitempty"`
	AwardDate     string                 `protobuf:"bytes,3,opt,name=award_date,json=awardDate,proto3" json:"award_date,omitempty"`
	AwardImageUrl string                 `protobuf:"bytes,4,opt,name=award_image_url,json=awardImageUrl,proto3" json:"award_image_url,omitempty"`
	AwardUid      uint64                 `protobuf:"varint,5,opt,name=award_uid,json=awardUid,proto3" json:"award_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Award) Reset() {
	*x = Award{}
	mi := &file_milpacs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Award) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Award) ProtoMessage() {}

func (x *Award) ProtoReflect() protoreflect.Message {
	mi := &file_milpacs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Award.ProtoReflect.Descriptor instead.
func (*Award) Descriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{10}
}

func (x *Award) GetAwardDetails() string {
	if x != nil {
		return x.AwardDetails
	}
	return ""
}

func (x *Award) GetAwardName() string {
	if x != nil {
		return x.AwardName
	}
	return ""
}

func (x *Award) GetAwardDate() string {
	if x != nil {
		return x.AwardDate
	}
	return ""
}

func (x *Award) GetAwardImageUrl() string {
	if x != nil {
		return x.AwardImageUrl
	}
	return ""
}

func (x *Award) GetAwardUid() uint64 {
	if x != nil {
		return x.AwardUid
	}
	return 0
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PositionTitle string                 `protobuf:"bytes,1,opt,name=position_title,json=positionTitle,proto3" json:"position_title,omitempty"`
	PositionId    uint64                 `protobuf:"varint,2,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_milpacs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_milpacs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{11}
}

func (x *Position) GetPositionTitle() string {
	if x != nil {
		return x.PositionTitle
	}
	return ""
}

func (x *Position) GetPositionId() uint64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

type LiteProfile struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	User              *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Rank              *Rank                  `protobuf:"bytes,2,opt,name=rank,proto3" json:"rank,omitempty"`
	RealName          string                 `protobuf:"bytes,3,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	UniformUrl        string                 `protobuf:"bytes,4,opt,name=uniform_url,json=uniformUrl,proto3" json:"uniform_url,omitempty"`
	Roster            RosterType             `protobuf:"varint,5,opt,name=roster,proto3,enum=proto.RosterType" json:"roster,omitempty"`
	Primary           *Position              `protobuf:"bytes,6,opt,name=primary,proto3" json:"primary,omitempty"`
	Secondaries       []*Position            `protobuf:"bytes,7,rep,name=secondaries,proto3" json:"secondaries,omitempty"`
	JoinDate          string                 `protobuf:"bytes,8,opt,name=join_date,json=joinDate,proto3" json:"join_date,omitempty"`
	PromotionDate     string                 `protobuf:"bytes,9,opt,name=promotion_date,json=promotionDate,proto3" json:"promotion_date,omitempty"`
	KeycloakId        string                 `protobuf:"bytes,10,opt,name=keycloak_id,json=keycloakId,proto3" json:"keycloak_id,omitempty"`
	DiscordId         string                 `protobuf:"bytes,11,opt,name=discord_id,json=discordId,proto3" json:"discord_id,omitempty"`
	AwardDate         string                 `protobuf:"bytes,12,opt,name=award_date,json=awardDate,proto3" json:"award_date,omitempty"`
	RecordDate        string                 `protobuf:"bytes,13,opt,name=record_date,json=recordDate,proto3" json:"record_date,omitempty"`
	LastForumPostDate string                 `protobuf:"bytes,14,opt,name=last_forum_post_date,json=lastForumPostDate,proto3" json:"last_forum_post_date,omitempty"`
	Mos               string                 `protobuf:"bytes,15,opt,name=mos,proto3" json:"mos,omitempty"`
	ConsoleGamertag   string                 `protobuf:"bytes,16,opt,name=console_gamertag,json=consoleGamertag,proto3" json:"console_gamertag,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LiteProfile) Reset() {
	*x = LiteProfile{}
	mi := &file_milpacs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiteProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiteProfile) ProtoMessage() {}

func (x *LiteProfile) ProtoReflect() protoreflect.Message {
	mi := &file_milpacs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiteProfile.ProtoReflect.Descriptor instead.
func (*LiteProfile) Descriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{12}
}

func (x *LiteProfile) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LiteProfile) GetRank() *Rank {
	if x != nil {
		return x.Rank
	}
	return nil
}

func (x *LiteProfile) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *LiteProfile) GetUniformUrl() string {
	if x != nil {
		return x.UniformUrl
	}
	return ""
}

func (x *LiteProfile) GetRoster() RosterType {
	if x != nil {
		return x.Roster
	}
	return RosterType_ROSTER_TYPE_UNSPECIFIED
}

func (x *LiteProfile) GetPrimary() *Position {
	if x != nil {
		return x.Primary
	}
	return nil
}

func (x *LiteProfile) GetSecondaries() []*Position {
	if x != nil {
		return x.Secondaries
	}
	return nil
}

func (x *LiteProfile) GetJoinDate() string {
	if x != nil {
		return x.JoinDate
	}
	return ""
}

func (x *LiteProfile) GetPromotionDate() string {
	if x != nil {
		return x.PromotionDate
	}
	return ""
}

func (x *LiteProfile) GetKeycloakId() string {
	if x != nil {
		return x.KeycloakId
	}
	return ""
}

func (x *LiteProfile) GetDiscordId() string {
	if x != nil {
		return x.DiscordId
	}
	return ""
}

func (x *LiteProfile) GetAwardDate() string {
	if x != nil {
		return x.AwardDate
	}
	return ""
}

func (x *LiteProfile) GetRecordDate() string {
	if x != nil {
		return x.RecordDate
	}
	return ""
}

func (x *LiteProfile) GetLastForumPostDate() string {
	if x != nil {
		return x.LastForumPostDate
	}
	return ""
}

func (x *LiteProfile) GetMos() string {
	if x != nil {
		return x.Mos
	}
	return ""
}

func (x *LiteProfile) GetConsoleGamertag() string {
	if x != nil {
		return x.ConsoleGamertag
	}
	return ""
}

type LiteRoster struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Profiles      map[uint64]*LiteProfile `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiteRoster) Reset() {
	*x = LiteRoster{}
	mi := &file_milpacs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiteRoster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiteRoster) ProtoMessage() {}

func (x *LiteRoster) ProtoReflect() protoreflect.Message {
	mi := &file_milpacs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiteRoster.ProtoReflect.Descriptor instead.
func (*LiteRoster) Descriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{13}
}

func (x *LiteRoster) GetProfiles() map[uint64]*LiteProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type PositionSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PositionQuery string                 `protobuf:"bytes,1,opt,name=position_query,json=positionQuery,proto3" json:"position_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionSearchRequest) Reset() {
	*x = PositionSearchRequest{}
	mi := &file_milpacs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionSearchRequest) ProtoMessage() {}

func (x *PositionSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_milpacs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionSearchRequest.ProtoReflect.Descriptor instead.
func (*PositionSearchRequest) Descriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{14}
}

func (x *PositionSearchRequest) GetPositionQuery() string {
	if x != nil {
		return x.PositionQuery
	}
	return ""
}

type S1UniformsRoster struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Profiles      map[uint64]*S1UniformsProfile `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S1UniformsRoster) Reset() {
	*x = S1UniformsRoster{}
	mi := &file_milpacs_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S1UniformsRoster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S1UniformsRoster) ProtoMessage() {}

func (x *S1UniformsRoster) ProtoReflect() protoreflect.Message {
	mi := &file_milpacs_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S1UniformsRoster.ProtoReflect.Descriptor instead.
func (*S1UniformsRoster) Descriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{15}
}

func (x *S1UniformsRoster) GetProfiles() map[uint64]*S1UniformsProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type S1UniformsProfile struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	User                     *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Rank                     *S1UniformsRank        `protobuf:"bytes,2,opt,name=rank,proto3" json:"rank,omitempty"`
	RealName                 string                 `protobuf:"bytes,3,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	UniformUrl               string                 `protobuf:"bytes,4,opt,name=uniform_url,json=uniformUrl,proto3" json:"uniform_url,omitempty"`
	UniformDate              string                 `protobuf:"bytes,5,opt,name=uniform_date,json=uniformDate,proto3" json:"uniform_date,omitempty"`
	UniformUpdateTriggerDate string                 `protobuf:"bytes,6,opt,name=uniform_update_trigger_date,json=uniformUpdateTriggerDate,proto3" json:"uniform_update_trigger_date,omitempty"`
	Roster                   RosterType             `protobuf:"varint,7,opt,name=roster,proto3,enum=proto.RosterType" json:"roster,omitempty"`
	PrimaryPositionTitle     string                 `protobuf:"bytes,8,opt,name=primary_position_title,json=primaryPositionTitle,proto3" json:"primary_position_title,omitempty"`
	Secondaries              []*S1UniformsPosition  `protobuf:"bytes,9,rep,name=secondaries,proto3" json:"secondaries,omitempty"`
	JoinDate                 string                 `protobuf:"bytes,10,opt,name=join_date,json=joinDate,proto3" json:"join_date,omitempty"`
	PromotionDate            string                 `protobuf:"bytes,11,opt,name=promotion_date,json=promotionDate,proto3" json:"promotion_date,omitempty"`
	AreaOfResponsibility     string                 `protobuf:"bytes,12,opt,name=area_of_responsibility,json=areaOfResponsibility,proto3" json:"area_of_responsibility,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *S1UniformsProfile) Reset() {
	*x = S1UniformsProfile{}
	mi := &file_milpacs_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S1UniformsProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S1UniformsProfile) ProtoMessage() {}

func (x *S1UniformsProfile) ProtoReflect() protoreflect.Message {
	mi := &file_milpacs_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S1UniformsProfile.ProtoReflect.Descriptor instead.
func (*S1UniformsProfile) Descriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{16}
}

func (x *S1UniformsProfile) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *S1UniformsProfile) GetRank() *S1UniformsRank {
	if x != nil {
		return x.Rank
	}
	return nil
}

func (x *S1UniformsProfile) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *S1UniformsProfile) GetUniformUrl() string {
	if x != nil {
		return x.UniformUrl
	}
	return ""
}

func (x *S1UniformsProfile) GetUniformDate() string {
	if x != nil {
		return x.UniformDate
	}
	return ""
}

func (x *S1UniformsProfile) GetUniformUpdateTriggerDate() string {
	if x != nil {
		return x.UniformUpdateTriggerDate
	}
	return ""
}

func (x *S1UniformsProfile) GetRoster() RosterType {
	if x != nil {
		return x.Roster
	}
	return RosterType_ROSTER_TYPE_UNSPECIFIED
}

func (x *S1UniformsProfile) GetPrimaryPositionTitle() string {
	if x != nil {
		return x.PrimaryPositionTitle
	}
	return ""
}

func (x *S1UniformsProfile) GetSecondaries() []*S1UniformsPosition {
	if x != nil {
		return x.Secondaries
	}
	return nil
}

func (x *S1UniformsProfile) GetJoinDate() string {
	if x != nil {
		return x.JoinDate
	}
	return ""
}

func (x *S1UniformsProfile) GetPromotionDate() string {
	if x != nil {
		return x.PromotionDate
	}
	return ""
}

func (x *S1UniformsProfile) GetAreaOfResponsibility() string {
	if x != nil {
		return x.AreaOfResponsibility
	}
	return ""
}

type S1UniformsRank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RankShort     string                 `protobuf:"bytes,1,opt,name=rank_short,json=rankShort,proto3" json:"rank_short,omitempty"`
	RankFull      string                 `protobuf:"bytes,2,opt,name=rank_full,json=rankFull,proto3" json:"rank_full,omitempty"`
	RankImageUrl  string                 `protobuf:"bytes,3,opt,name=rank_image_url,json=rankImageUrl,proto3" json:"rank_image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S1UniformsRank) Reset() {
	*x = S1UniformsRank{}
	mi := &file_milpacs_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S1UniformsRank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S1UniformsRank) ProtoMessage() {}

func (x *S1UniformsRank) ProtoReflect() protoreflect.Message {
	mi := &file_milpacs_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S1UniformsRank.ProtoReflect.Descriptor instead.
func (*S1UniformsRank) Descriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{17}
}

func (x *S1UniformsRank) GetRankShort() string {
	if x != nil {
		return x.RankShort
	}
	return ""
}

func (x *S1UniformsRank) GetRankFull() string {
	if x != nil {
		return x.RankFull
	}
	return ""
}

func (x *S1UniformsRank) GetRankImageUrl() string {
	if x != nil {
		return x.RankImageUrl
	}
	return ""
}

type S1UniformsPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PositionTitle string                 `protobuf:"bytes,1,opt,name=position_title,json=positionTitle,proto3" json:"position_title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S1UniformsPosition) Reset() {
	*x = S1UniformsPosition{}
	mi := &file_milpacs_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S1UniformsPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S1UniformsPosition) ProtoMessage() {}

func (x *S1UniformsPosition) ProtoReflect() protoreflect.Message {
	mi := &file_milpacs_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S1UniformsPosition.ProtoReflect.Descriptor instead.
func (*S1UniformsPosition) Descriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{18}
}

func (x *S1UniformsPosition) GetPositionTitle() string {
	if x != nil {
		return x.PositionTitle
	}
	return ""
}

type RanksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ranks         []*RankExpanded        `protobuf:"bytes,1,rep,name=ranks,proto3" json:"ranks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RanksResponse) Reset() {
	*x = RanksResponse{}
	mi := &file_milpacs_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RanksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RanksResponse) ProtoMessage() {}

func (x *RanksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_milpacs_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RanksResponse.ProtoReflect.Descriptor instead.
func (*RanksResponse) Descriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{19}
}

func (x *RanksResponse) GetRanks() []*RankExpanded {
	if x != nil {
		return x.Ranks
	}
	return nil
}

type PositionGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*PositionGroup       `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionGroupsResponse) Reset() {
	*x = PositionGroupsResponse{}
	mi := &file_milpacs_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionGroupsResponse) ProtoMessage() {}

func (x *PositionGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_milpacs_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionGroupsResponse.ProtoReflect.Descriptor instead.
func (*PositionGroupsResponse) Descriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{20}
}

func (x *PositionGroupsResponse) GetGroups() []*PositionGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

type PositionGroup struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GroupId           uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupTitle        string                 `protobuf:"bytes,2,opt,name=group_title,json=groupTitle,proto3" json:"group_title,omitempty"`
	GroupDisplayOrder uint32                 `protobuf:"varint,3,opt,name=group_display_order,json=groupDisplayOrder,proto3" json:"group_display_order,omitempty"`
	Positions         []*PositionExpanded    `protobuf:"bytes,4,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PositionGroup) Reset() {
	*x = PositionGroup{}
	mi := &file_milpacs_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionGroup) ProtoMessage() {}

func (x *PositionGroup) ProtoReflect() protoreflect.Message {
	mi := &file_milpacs_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionGroup.ProtoReflect.Descriptor instead.
func (*PositionGroup) Descriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{21}
}

func (x *PositionGroup) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *PositionGroup) GetGroupTitle() string {
	if x != nil {
		return x.GroupTitle
	}
	return ""
}

func (x *PositionGroup) GetGroupDisplayOrder() uint32 {
	if x != nil {
		return x.GroupDisplayOrder
	}
	return 0
}

func (x *PositionGroup) GetPositions() []*PositionExpanded {
	if x != nil {
		return x.Positions
	}
	return nil
}

type RankExpanded struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RankShort        string                 `protobuf:"bytes,1,opt,name=rank_short,json=rankShort,proto3" json:"rank_short,omitempty"`
	RankFull         string                 `protobuf:"bytes,2,opt,name=rank_full,json=rankFull,proto3" json:"rank_full,omitempty"`
	RankImageUrl     string                 `protobuf:"bytes,3,opt,name=rank_image_url,json=rankImageUrl,proto3" json:"rank_image_url,omitempty"`
	RankId           uint64                 `protobuf:"varint,4,opt,name=rank_id,json=rankId,proto3" json:"rank_id,omitempty"`
	RankDisplayOrder uint32                 `protobuf:"varint,5,opt,name=rank_display_order,json=rankDisplayOrder,proto3" json:"rank_display_order,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RankExpanded) Reset() {
	*x = RankExpanded{}
	mi := &file_milpacs_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankExpanded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankExpanded) ProtoMessage() {}

func (x *RankExpanded) ProtoReflect() protoreflect.Message {
	mi := &file_milpacs_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankExpanded.ProtoReflect.Descriptor instead.
func (*RankExpanded) Descriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{22}
}

func (x *RankExpanded) GetRankShort() string {
	if x != nil {
		return x.RankShort
	}
	return ""
}

func (x *RankExpanded) GetRankFull() string {
	if x != nil {
		return x.RankFull
	}
	return ""
}

func (x *RankExpanded) GetRankImageUrl() string {
	if x != nil {
		return x.RankImageUrl
	}
	return ""
}

func (x *RankExpanded) GetRankId() uint64 {
	if x != nil {
		return x.RankId
	}
	return 0
}

func (x *RankExpanded) GetRankDisplayOrder() uint32 {
	if x != nil {
		return x.RankDisplayOrder
	}
	return 0
}

type PositionExpanded struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	PositionTitle             string                 `protobuf:"bytes,1,opt,name=position_title,json=positionTitle,proto3" json:"position_title,omitempty"`
	PositionId                uint64                 `protobuf:"varint,2,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	PositionDisplayOrder      uint32                 `protobuf:"varint,3,opt,name=position_display_order,json=positionDisplayOrder,proto3" json:"position_display_order,omitempty"`
	PositionPossibleSecondary bool                   `protobuf:"varint,4,opt,name=position_possible_secondary,json=positionPossibleSecondary,proto3" json:"position_possible_secondary,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *PositionExpanded) Reset() {
	*x = PositionExpanded{}
	mi := &file_milpacs_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionExpanded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionExpanded) ProtoMessage() {}

func (x *PositionExpanded) ProtoReflect() protoreflect.Message {
	mi := &file_milpacs_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionExpanded.ProtoReflect.Descriptor instead.
func (*PositionExpanded) Descriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{23}
}

func (x *PositionExpanded) GetPositionTitle() string {
	if x != nil {
		return x.PositionTitle
	}
	return ""
}

func (x *PositionExpanded) GetPositionId() uint64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

func (x *PositionExpanded) GetPositionDisplayOrder() uint32 {
	if x != nil {
		return x.PositionDisplayOrder
	}
	return 0
}

func (x *PositionExpanded) GetPositionPossibleSecondary() bool {
	if x != nil {
		return x.PositionPossibleSecondary
	}
	return false
}

type AwolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Awols         []*Awol                `protobuf:"bytes,1,rep,name=awols,proto3" json:"awols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwolResponse) Reset() {
	*x = AwolResponse{}
	mi := &file_milpacs_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwolResponse) ProtoMessage() {}

func (x *AwolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_milpacs_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwolResponse.ProtoReflect.Descriptor instead.
func (*AwolResponse) Descriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{24}
}

func (x *AwolResponse) GetAwols() []*Awol {
	if x != nil {
		return x.Awols
	}
	return nil
}

type Awol struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupName     string                 `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	RankName      string                 `protobuf:"bytes,2,opt,name=rank_name,json=rankName,proto3" json:"rank_name,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	UserId        uint64                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	HumanDate     string                 `protobuf:"bytes,5,opt,name=human_date,json=humanDate,proto3" json:"human_date,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PostId        uint64                 `protobuf:"varint,7,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	MilpacId      uint64                 `protobuf:"varint,8,opt,name=milpac_id,json=milpacId,proto3" json:"milpac_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Awol) Reset() {
	*x = Awol{}
	mi := &file_milpacs_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Awol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Awol) ProtoMessage() {}

func (x *Awol) ProtoReflect() protoreflect.Message {
	mi := &file_milpacs_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Awol.ProtoReflect.Descriptor instead.
func (*Awol) Descriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{25}
}

func (x *Awol) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *Awol) GetRankName() string {
	if x != nil {
		return x.RankName
	}
	return ""
}

func (x *Awol) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Awol) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Awol) GetHumanDate() string {
	if x != nil {
		return x.HumanDate
	}
	return ""
}

func (x *Awol) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Awol) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *Awol) GetMilpacId() uint64 {
	if x != nil {
		return x.MilpacId
	}
	return 0
}

type GamertagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gamertag      string                 `protobuf:"bytes,1,opt,name=gamertag,proto3" json:"gamertag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GamertagRequest) Reset() {
	*x = GamertagRequest{}
	mi := &file_milpacs_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GamertagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamertagRequest) ProtoMessage() {}

func (x *GamertagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_milpacs_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamertagRequest.ProtoReflect.Descriptor instead.
func (*GamertagRequest) Descriptor() ([]byte, []int) {
	return file_milpacs_proto_rawDescGZIP(), []int{26}
}

func (x *GamertagRequest) GetGamertag() string {
	if x != nil {
		return x.Gamertag
	}
	return ""
}

var File_milpacs_proto protoreflect.FileDescriptor

const file_milpacs_proto_rawDesc = "" +
	"\n" +
	"\rmilpacs.proto\x12\x05proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"E\n" +
	"\x0eProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"4\n" +
	"\x11KeycloakIdRequest\x12\x1f\n" +
	"\vkeycloak_id\x18\x01 \x01(\tR\n" +
	"keycloakId\"1\n" +
	"\x10DiscordIdRequest\x12\x1d\n" +
	"\n" +
	"discord_id\x18\x01 \x01(\tR\tdiscordId\"\x81\x01\n" +
	"\x04Rank\x12\x1d\n" +
	"\n" +
	"rank_short\x18\x01 \x01(\tR\trankShort\x12\x1b\n" +
	"\trank_full\x18\x02 \x01(\tR\brankFull\x12$\n" +
	"\x0erank_image_url\x18\x03 \x01(\tR\frankImageUrl\x12\x17\n" +
	"\arank_id\x18\x04 \x01(\x04R\x06rankId\"\x1a\n" +
	"\x06Thingy\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\tR\x03ack\"\xd3\x04\n" +
	"\aProfile\x12\x1f\n" +
	"\x04user\x18\x01 \x01(\v2\v.proto.UserR\x04user\x12\x1f\n" +
	"\x04rank\x18\x02 \x01(\v2\v.proto.RankR\x04rank\x12\x1b\n" +
	"\treal_name\x18\x03 \x01(\tR\brealName\x12\x1f\n" +
	"\vuniform_url\x18\x04 \x01(\tR\n" +
	"uniformUrl\x12)\n" +
	"\x06roster\x18\x05 \x01(\x0e2\x11.proto.RosterTypeR\x06roster\x12)\n" +
	"\aprimary\x18\x06 \x01(\v2\x0f.proto.PositionR\aprimary\x121\n" +
	"\vsecondaries\x18\a \x03(\v2\x0f.proto.PositionR\vsecondaries\x12'\n" +
	"\arecords\x18\b \x03(\v2\r.proto.RecordR\arecords\x12$\n" +
	"\x06awards\x18\t \x03(\v2\f.proto.AwardR\x06awards\x12\x1b\n" +
	"\tjoin_date\x18\n" +
	" \x01(\tR\bjoinDate\x12%\n" +
	"\x0epromotion_date\x18\v \x01(\tR\rpromotionDate\x12\x1f\n" +
	"\vkeycloak_id\x18\f \x01(\tR\n" +
	"keycloakId\x12\x1d\n" +
	"\n" +
	"discord_id\x18\r \x01(\tR\tdiscordId\x12/\n" +
	"\x14last_forum_post_date\x18\x0e \x01(\tR\x11lastForumPostDate\x12\x10\n" +
	"\x03mos\x18\x0f \x01(\tR\x03mos\x12)\n" +
	"\x10console_gamertag\x18\x10 \x01(\tR\x0fconsoleGamertag\":\n" +
	"\rRosterRequest\x12)\n" +
	"\x06roster\x18\x01 \x01(\x0e2\x11.proto.RosterTypeR\x06roster\"\x8e\x01\n" +
	"\x06Roster\x127\n" +
	"\bprofiles\x18\x01 \x03(\v2\x1b.proto.Roster.ProfilesEntryR\bprofiles\x1aK\n" +
	"\rProfilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.proto.ProfileR\x05value:\x028\x01\";\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\xa3\x01\n" +
	"\x06Record\x12%\n" +
	"\x0erecord_details\x18\x01 \x01(\tR\rrecordDetails\x122\n" +
	"\vrecord_type\x18\x02 \x01(\x0e2\x11.proto.RecordTypeR\n" +
	"recordType\x12\x1f\n" +
	"\vrecord_date\x18\x03 \x01(\tR\n" +
	"recordDate\x12\x1d\n" +
	"\n" +
	"record_uid\x18\x04 \x01(\x04R\trecordUid\"\xaf\x01\n" +
	"\x05Award\x12#\n" +
	"\raward_details\x18\x01 \x01(\tR\fawardDetails\x12\x1d\n" +
	"\n" +
	"award_name\x18\x02 \x01(\tR\tawardName\x12\x1d\n" +
	"\n" +
	"award_date\x18\x03 \x01(\tR\tawardDate\x12&\n" +
	"\x0faward_image_url\x18\x04 \x01(\tR\rawardImageUrl\x12\x1b\n" +
	"\taward_uid\x18\x05 \x01(\x04R\bawardUid\"R\n" +
	"\bPosition\x12%\n" +
	"\x0eposition_title\x18\x01 \x01(\tR\rpositionTitle\x12\x1f\n" +
	"\vposition_id\x18\x02 \x01(\x04R\n" +
	"positionId\"\xc8\x04\n" +
	"\vLiteProfile\x12\x1f\n" +
	"\x04user\x18\x01 \x01(\v2\v.proto.UserR\x04user\x12\x1f\n" +
	"\x04rank\x18\x02 \x01(\v2\v.proto.RankR\x04rank\x12\x1b\n" +
	"\treal_name\x18\x03 \x01(\tR\brealName\x12\x1f\n" +
	"\vuniform_url\x18\x04 \x01(\tR\n" +
	"uniformUrl\x12)\n" +
	"\x06roster\x18\x05 \x01(\x0e2\x11.proto.RosterTypeR\x06roster\x12)\n" +
	"\aprimary\x18\x06 \x01(\v2\x0f.proto.PositionR\aprimary\x121\n" +
	"\vsecondaries\x18\a \x03(\v2\x0f.proto.PositionR\vsecondaries\x12\x1b\n" +
	"\tjoin_date\x18\b \x01(\tR\bjoinDate\x12%\n" +
	"\x0epromotion_date\x18\t \x01(\tR\rpromotionDate\x12\x1f\n" +
	"\vkeycloak_id\x18\n" +
	" \x01(\tR\n" +
	"keycloakId\x12\x1d\n" +
	"\n" +
	"discord_id\x18\v \x01(\tR\tdiscordId\x12\x1d\n" +
	"\n" +
	"award_date\x18\f \x01(\tR\tawardDate\x12\x1f\n" +
	"\vrecord_date\x18\r \x01(\tR\n" +
	"recordDate\x12/\n" +
	"\x14last_forum_post_date\x18\x0e \x01(\tR\x11lastForumPostDate\x12\x10\n" +
	"\x03mos\x18\x0f \x01(\tR\x03mos\x12)\n" +
	"\x10console_gamertag\x18\x10 \x01(\tR\x0fconsoleGamertag\"\x9a\x01\n" +
	"\n" +
	"LiteRoster\x12;\n" +
	"\bprofiles\x18\x01 \x03(\v2\x1f.proto.LiteRoster.ProfilesEntryR\bprofiles\x1aO\n" +
	"\rProfilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.proto.LiteProfileR\x05value:\x028\x01\">\n" +
	"\x15PositionSearchRequest\x12%\n" +
	"\x0eposition_query\x18\x01 \x01(\tR\rpositionQuery\"\xac\x01\n" +
	"\x10S1UniformsRoster\x12A\n" +
	"\bprofiles\x18\x01 \x03(\v2%.proto.S1UniformsRoster.ProfilesEntryR\bprofiles\x1aU\n" +
	"\rProfilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.proto.S1UniformsProfileR\x05value:\x028\x01\"\x97\x04\n" +
	"\x11S1UniformsProfile\x12\x1f\n" +
	"\x04user\x18\x01 \x01(\v2\v.proto.UserR\x04user\x12)\n" +
	"\x04rank\x18\x02 \x01(\v2\x15.proto.S1UniformsRankR\x04rank\x12\x1b\n" +
	"\treal_name\x18\x03 \x01(\tR\brealName\x12\x1f\n" +
	"\vuniform_url\x18\x04 \x01(\tR\n" +
	"uniformUrl\x12!\n" +
	"\funiform_date\x18\x05 \x01(\tR\vuniformDate\x12=\n" +
	"\x1buniform_update_trigger_date\x18\x06 \x01(\tR\x18uniformUpdateTriggerDate\x12)\n" +
	"\x06roster\x18\a \x01(\x0e2\x11.proto.RosterTypeR\x06roster\x124\n" +
	"\x16primary_position_title\x18\b \x01(\tR\x14primaryPositionTitle\x12;\n" +
	"\vsecondaries\x18\t \x03(\v2\x19.proto.S1UniformsPositionR\vsecondaries\x12\x1b\n" +
	"\tjoin_date\x18\n" +
	" \x01(\tR\bjoinDate\x12%\n" +
	"\x0epromotion_date\x18\v \x01(\tR\rpromotionDate\x124\n" +
	"\x16area_of_responsibility\x18\f \x01(\tR\x14areaOfResponsibility\"r\n" +
	"\x0eS1UniformsRank\x12\x1d\n" +
	"\n" +
	"rank_short\x18\x01 \x01(\tR\trankShort\x12\x1b\n" +
	"\trank_full\x18\x02 \x01(\tR\brankFull\x12$\n" +
	"\x0erank_image_url\x18\x03 \x01(\tR\frankImageUrl\";\n" +
	"\x12S1UniformsPosition\x12%\n" +
	"\x0eposition_title\x18\x01 \x01(\tR\rpositionTitle\":\n" +
	"\rRanksResponse\x12)\n" +
	"\x05ranks\x18\x01 \x03(\v2\x13.proto.RankExpandedR\x05ranks\"F\n" +
	"\x16PositionGroupsResponse\x12,\n" +
	"\x06groups\x18\x01 \x03(\v2\x14.proto.PositionGroupR\x06groups\"\xb2\x01\n" +
	"\rPositionGroup\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12\x1f\n" +
	"\vgroup_title\x18\x02 \x01(\tR\n" +
	"groupTitle\x12.\n" +
	"\x13group_display_order\x18\x03 \x01(\rR\x11groupDisplayOrder\x125\n" +
	"\tpositions\x18\x04 \x03(\v2\x17.proto.PositionExpandedR\tpositions\"\xb7\x01\n" +
	"\fRankExpanded\x12\x1d\n" +
	"\n" +
	"rank_short\x18\x01 \x01(\tR\trankShort\x12\x1b\n" +
	"\trank_full\x18\x02 \x01(\tR\brankFull\x12$\n" +
	"\x0erank_image_url\x18\x03 \x01(\tR\frankImageUrl\x12\x17\n" +
	"\arank_id\x18\x04 \x01(\x04R\x06rankId\x12,\n" +
	"\x12rank_display_order\x18\x05 \x01(\rR\x10rankDisplayOrder\"\xd0\x01\n" +
	"\x10PositionExpanded\x12%\n" +
	"\x0eposition_title\x18\x01 \x01(\tR\rpositionTitle\x12\x1f\n" +
	"\vposition_id\x18\x02 \x01(\x04R\n" +
	"positionId\x124\n" +
	"\x16position_display_order\x18\x03 \x01(\rR\x14positionDisplayOrder\x12>\n" +
	"\x1bposition_possible_secondary\x18\x04 \x01(\bR\x19positionPossibleSecondary\"1\n" +
	"\fAwolResponse\x12!\n" +
	"\x05awols\x18\x01 \x03(\v2\v.proto.AwolR\x05awols\"\xea\x01\n" +
	"\x04Awol\x12\x1d\n" +
	"\n" +
	"group_name\x18\x01 \x01(\tR\tgroupName\x12\x1b\n" +
	"\trank_name\x18\x02 \x01(\tR\brankName\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"human_date\x18\x05 \x01(\tR\thumanDate\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x04R\ttimestamp\x12\x17\n" +
	"\apost_id\x18\a \x01(\x04R\x06postId\x12\x1b\n" +
	"\tmilpac_id\x18\b \x01(\x04R\bmilpacId\"-\n" +
	"\x0fGamertagRequest\x12\x1a\n" +
	"\bgamertag\x18\x01 \x01(\tR\bgamertag*\xc8\x01\n" +
	"\n" +
	"RosterType\x12\x1b\n" +
	"\x17ROSTER_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ROSTER_TYPE_COMBAT\x10\x01\x12\x17\n" +
	"\x13ROSTER_TYPE_RESERVE\x10\x02\x12\x14\n" +
	"\x10ROSTER_TYPE_ELOA\x10\x03\x12\x1d\n" +
	"\x19ROSTER_TYPE_WALL_OF_HONOR\x10\x04\x12\x19\n" +
	"\x15ROSTER_TYPE_ARLINGTON\x10\x05\x12\x1c\n" +
	"\x18ROSTER_TYPE_PAST_MEMBERS\x10\x06*\x9d\x02\n" +
	"\n" +
	"RecordType\x12\x1b\n" +
	"\x17RECORD_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15RECORD_TYPE_PROMOTION\x10\x01\x12\x19\n" +
	"\x15RECORD_TYPE_OPERATION\x10\x02\x12\x18\n" +
	"\x14RECORD_TYPE_TRANSFER\x10\x03\x12\x1c\n" +
	"\x18RECORD_TYPE_DISCIPLINARY\x10\x04\x12\x19\n" +
	"\x15RECORD_TYPE_DISCHARGE\x10\x05\x12\x1a\n" +
	"\x16RECORD_TYPE_ASSIGNMENT\x10\x06\x12\x1b\n" +
	"\x17RECORD_TYPE_NAME_CHANGE\x10\a\x12\x14\n" +
	"\x10RECORD_TYPE_ELOA\x10\b\x12\x1a\n" +
	"\x16RECORD_TYPE_GRADUATION\x10\t*\xc9\x04\n" +
	"\bRankType\x12\x19\n" +
	"\x15RANK_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rRANK_TYPE_GOA\x10\x01\x12\x11\n" +
	"\rRANK_TYPE_GEN\x10\x02\x12\x11\n" +
	"\rRANK_TYPE_LTG\x10\x03\x12\x10\n" +
	"\fRANK_TYPE_MG\x10\x04\x12\x10\n" +
	"\fRANK_TYPE_BG\x10\x05\x12\x11\n" +
	"\rRANK_TYPE_COL\x10\x06\x12\x11\n" +
	"\rRANK_TYPE_LTC\x10\a\x12\x11\n" +
	"\rRANK_TYPE_MAJ\x10\b\x12\x11\n" +
	"\rRANK_TYPE_CPT\x10\t\x12\x11\n" +
	"\rRANK_TYPE_1LT\x10\n" +
	"\x12\x11\n" +
	"\rRANK_TYPE_2LT\x10\v\x12\x11\n" +
	"\rRANK_TYPE_CSM\x10\f\x12\x11\n" +
	"\rRANK_TYPE_SGM\x10\r\x12\x11\n" +
	"\rRANK_TYPE_1SG\x10\x0e\x12\x11\n" +
	"\rRANK_TYPE_MSG\x10\x0f\x12\x11\n" +
	"\rRANK_TYPE_SFC\x10\x10\x12\x11\n" +
	"\rRANK_TYPE_SSG\x10\x11\x12\x11\n" +
	"\rRANK_TYPE_SGT\x10\x12\x12\x11\n" +
	"\rRANK_TYPE_CPL\x10\x13\x12\x11\n" +
	"\rRANK_TYPE_SPC\x10\x14\x12\x11\n" +
	"\rRANK_TYPE_PFC\x10\x15\x12\x11\n" +
	"\rRANK_TYPE_PVT\x10\x16\x12\x11\n" +
	"\rRANK_TYPE_RCT\x10\x17\x12\x11\n" +
	"\rRANK_TYPE_CW5\x10\x1a\x12\x11\n" +
	"\rRANK_TYPE_CW4\x10\x1b\x12\x11\n" +
	"\rRANK_TYPE_CW3\x10\x1c\x12\x11\n" +
	"\rRANK_TYPE_CW2\x10\x1d\x12\x11\n" +
	"\rRANK_TYPE_WO1\x10\x1e\x12\x10\n" +
	"\fRANK_TYPE_AR\x10\x1f2\xb3\x14\n" +
	"\rMilpacService\x12\xf9\x01\n" +
	"\n" +
	"GetProfile\x12\x15.proto.ProfileRequest\x1a\x0e.proto.Profile\"\xc3\x01\x92Ae\n" +
	"\x17Users, Milpacs, Profile\x12\x1dGet given user milpac Profile\x1a+Get milpac Profile data for a specific user\x82\xd3\xe4\x93\x02UZ-\x12+/api/v1/milpacs/profile/username/{username}\x12$/api/v1/milpacs/profile/id/{user_id}\x12\xa9\x01\n" +
	"\tGetRoster\x12\x14.proto.RosterRequest\x1a\r.proto.Roster\"w\x92AU\n" +
	"\x0fRoster, Milpacs\x12\x12Get a given roster\x1a.Get all milpac Profile data for a given roster\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/roster/{roster}\x12\xf9\x01\n" +
	"\x14GetUserViaKeycloakId\x12\x18.proto.KeycloakIdRequest\x1a\x0e.proto.Profile\"\xb6\x01\x92A\x85\x01\n" +
	"\x19Roster, Milpacs, Keycloak\x12$Get a Milpac profile via keycloak ID\x1aBGet all milpac Profile data for a given user via their Keycloak ID\x82\xd3\xe4\x93\x02'\x12%/api/v1/milpac/keycloak/{keycloak_id}\x12\xf2\x01\n" +
	"\x13GetUserViaDiscordId\x12\x17.proto.DiscordIdRequest\x1a\x0e.proto.Profile\"\xb1\x01\x92A\x82\x01\n" +
	"\x18Roster, Milpacs, Discord\x12#Get a Milpac profile via Discord ID\x1aAGet all milpac Profile data for a given user via their Discord ID\x82\xd3\xe4\x93\x02%\x12#/api/v1/milpac/discord/{discord_id}\x12\xf2\x01\n" +
	"\rGetLiteRoster\x12\x14.proto.RosterRequest\x1a\x11.proto.LiteRoster\"\xb7\x01\x92A\x8f\x01\n" +
	"\x0fRoster, Milpacs\x12,Get a given roster with minimal profile data\x1aNGet basic milpac Profile data for a given roster, excluding records and awards\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/roster/{roster}/lite\x12\xbf\x02\n" +
	"\x10SearchByPosition\x12\x1c.proto.PositionSearchRequest\x1a\x11.proto.LiteRoster\"\xf9\x01\x92A\xba\x01\n" +
	"\x18Users, Milpacs, Position\x12%Search for profiles by position title\x1awSearch for profiles using fuzzy matching on primary and secondary position titles, returns lite profiles for efficiency\x82\xd3\xe4\x93\x025\x123/api/v1/milpacs/position/search/{position_query=**}\x12\xef\x01\n" +
	"\x13GetS1UniformsRoster\x12\x14.proto.RosterRequest\x1a\x17.proto.S1UniformsRoster\"\xa8\x01\x92A\x80\x01\n" +
	"\x13Roster, Milpacs, S1\x12,Get a given roster with minimal profile data\x1a;Get the specified roster with data tailored for S1 Uniforms\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/s1/uniforms/{roster}\x12\xa7\x01\n" +
	"\vGetAllRanks\x12\x16.google.protobuf.Empty\x1a\x14.proto.RanksResponse\"j\x92AJ\n" +
	"\x0eRanks, Milpacs\x12\rGet all ranks\x1a)Get a list of all ranks and their details\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/milpacs/ranks\x12\x83\x02\n" +
	"\x11GetPositionGroups\x12\x16.google.protobuf.Empty\x1a\x1d.proto.PositionGroupsResponse\"\xb6\x01\x92A\x8b\x01\n" +
	"\x12Positions, Milpacs\x12&Get all position groups with positions\x1aMGet a hierarchical list of all position groups and their associated positions\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/milpacs/position/groups\x12\xc1\x01\n" +
	"\aGetAwol\x12\x16.google.protobuf.Empty\x1a\x13.proto.AwolResponse\"\x88\x01\x92Ai\n" +
	"\x0eAWOLs, Milpacs\x12\x15Get all AWOL troopers\x1a@Get a list of all troopers that havent posted in the last 7 days\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/milpacs/awol\x12\xeb\x01\n" +
	"\x12GetGamertagProfile\x12\x16.proto.GamertagRequest\x1a\x0e.proto.Profile\"\xac\x01\x92A\x7f\n" +
	"\x19Roster, Milpacs, Gamertag\x12!Get a Milpac profile via Gamertag\x1a?Get all milpac Profile data for a given user via their Gamertag\x82\xd3\xe4\x93\x02$\x12\"/api/v1/milpac/gamertag/{gamertag}B\xc6\x01\x92A\xa7\x01\x12\x052\x03dev*\x01\x02ZY\n" +
	"W\n" +
	"\x06bearer\x12M\b\x02\x128Authentication token, prefixed by Bearer: Bearer <token>\x1a\rAuthorization \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00r2\n" +
	"\x137Cav API Repository\x12\x1bhttps://github.com/7cav/apiZ\x19github.com/7cav/api/protob\x06proto3"

var (
	file_milpacs_proto_rawDescOnce sync.Once
	file_milpacs_proto_rawDescData []byte
)

func file_milpacs_proto_rawDescGZIP() []byte {
	file_milpacs_proto_rawDescOnce.Do(func() {
		file_milpacs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_milpacs_proto_rawDesc), len(file_milpacs_proto_rawDesc)))
	})
	return file_milpacs_proto_rawDescData
}

var file_milpacs_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_milpacs_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_milpacs_proto_goTypes = []any{
	(RosterType)(0),                // 0: proto.RosterType
	(RecordType)(0),                // 1: proto.RecordType
	(RankType)(0),                  // 2: proto.RankType
	(*ProfileRequest)(nil),         // 3: proto.ProfileRequest
	(*KeycloakIdRequest)(nil),      // 4: proto.KeycloakIdRequest
	(*DiscordIdRequest)(nil),       // 5: proto.DiscordIdRequest
	(*Rank)(nil),                   // 6: proto.Rank
	(*Thingy)(nil),                 // 7: proto.Thingy
	(*Profile)(nil),                // 8: proto.Profile
	(*RosterRequest)(nil),          // 9: proto.RosterRequest
	(*Roster)(nil),                 // 10: proto.Roster
	(*User)(nil),                   // 11: proto.User
	(*Record)(nil),                 // 12: proto.Record
	(*Award)(nil),                  // 13: proto.Award
	(*Position)(nil),               // 14: proto.Position
	(*LiteProfile)(nil),            // 15: proto.LiteProfile
	(*LiteRoster)(nil),             // 16: proto.LiteRoster
	(*PositionSearchRequest)(nil),  // 17: proto.PositionSearchRequest
	(*S1UniformsRoster)(nil),       // 18: proto.S1UniformsRoster
	(*S1UniformsProfile)(nil),      // 19: proto.S1UniformsProfile
	(*S1UniformsRank)(nil),         // 20: proto.S1UniformsRank
	(*S1UniformsPosition)(nil),     // 21: proto.S1UniformsPosition
	(*RanksResponse)(nil),          // 22: proto.RanksResponse
	(*PositionGroupsResponse)(nil), // 23: proto.PositionGroupsResponse
	(*PositionGroup)(nil),          // 24: proto.PositionGroup
	(*RankExpanded)(nil),           // 25: proto.RankExpanded
	(*PositionExpanded)(nil),       // 26: proto.PositionExpanded
	(*AwolResponse)(nil),           // 27: proto.AwolResponse
	(*Awol)(nil),                   // 28: proto.Awol
	(*GamertagRequest)(nil),        // 29: proto.GamertagRequest
	nil,                            // 30: proto.Roster.ProfilesEntry
	nil,                            // 31: proto.LiteRoster.ProfilesEntry
	nil,                            // 32: proto.S1UniformsRoster.ProfilesEntry
	(*emptypb.Empty)(nil),          // 33: google.protobuf.Empty
}
var file_milpacs_proto_depIdxs = []int32{
	11, // 0: proto.Profile.user:type_name -> proto.User
	6,  // 1: proto.Profile.rank:type_name -> proto.Rank
	0,  // 2: proto.Profile.roster:type_name -> proto.RosterType
	14, // 3: proto.Profile.primary:type_name -> proto.Position
	14, // 4: proto.Profile.secondaries:type_name -> proto.Position
	12, // 5: proto.Profile.records:type_name -> proto.Record
	13, // 6: proto.Profile.awards:type_name -> proto.Award
	0,  // 7: proto.RosterRequest.roster:type_name -> proto.RosterType
	30, // 8: proto.Roster.profiles:type_name -> proto.Roster.ProfilesEntry
	1,  // 9: proto.Record.record_type:type_name -> proto.RecordType
	11, // 10: proto.LiteProfile.user:type_name -> proto.User
	6,  // 11: proto.LiteProfile.rank:type_name -> proto.Rank
	0,  // 12: proto.LiteProfile.roster:type_name -> proto.RosterType
	14, // 13: proto.LiteProfile.primary:type_name -> proto.Position
	14, // 14: proto.LiteProfile.secondaries:type_name -> proto.Position
	31, // 15: proto.LiteRoster.profiles:type_name -> proto.LiteRoster.ProfilesEntry
	32, // 16: proto.S1UniformsRoster.profiles:type_name -> proto.S1UniformsRoster.ProfilesEntry
	11, // 17: proto.S1UniformsProfile.user:type_name -> proto.User
	20, // 18: proto.S1UniformsProfile.rank:type_name -> proto.S1UniformsRank
	0,  // 19: proto.S1UniformsProfile.roster:type_name -> proto.RosterType
	21, // 20: proto.S1UniformsProfile.secondaries:type_name -> proto.S1UniformsPosition
	25, // 21: proto.RanksResponse.ranks:type_name -> proto.RankExpanded
	24, // 22: proto.PositionGroupsResponse.groups:type_name -> proto.PositionGroup
	26, // 23: proto.PositionGroup.positions:type_name -> proto.PositionExpanded
	28, // 24: proto.AwolResponse.awols:type_name -> proto.Awol
	8,  // 25: proto.Roster.ProfilesEntry.value:type_name -> proto.Profile
	15, // 26: proto.LiteRoster.ProfilesEntry.value:type_name -> proto.LiteProfile
	19, // 27: proto.S1UniformsRoster.ProfilesEntry.value:type_name -> proto.S1UniformsProfile
	3,  // 28: proto.MilpacService.GetProfile:input_type -> proto.ProfileRequest
	9,  // 29: proto.MilpacService.GetRoster:input_type -> proto.RosterRequest
	4,  // 30: proto.MilpacService.GetUserViaKeycloakId:input_type -> proto.KeycloakIdRequest
	5,  // 31: proto.MilpacService.GetUserViaDiscordId:input_type -> proto.DiscordIdRequest
	9,  // 32: proto.MilpacService.GetLiteRoster:input_type -> proto.RosterRequest
	17, // 33: proto.MilpacService.SearchByPosition:input_type -> proto.PositionSearchRequest
	9,  // 34: proto.MilpacService.GetS1UniformsRoster:input_type -> proto.RosterRequest
	33, // 35: proto.MilpacService.GetAllRanks:input_type -> google.protobuf.Empty
	33, // 36: proto.MilpacService.GetPositionGroups:input_type -> google.protobuf.Empty
	33, // 37: proto.MilpacService.GetAwol:input_type -> google.protobuf.Empty
	29, // 38: proto.MilpacService.GetGamertagProfile:input_type -> proto.GamertagRequest
	8,  // 39: proto.MilpacService.GetProfile:output_type -> proto.Profile
	10, // 40: proto.MilpacService.GetRoster:output_type -> proto.Roster
	8,  // 41: proto.MilpacService.GetUserViaKeycloakId:output_type -> proto.Profile
	8,  // 42: proto.MilpacService.GetUserViaDiscordId:output_type -> proto.Profile
	16, // 43: proto.MilpacService.GetLiteRoster:output_type -> proto.LiteRoster
	16, // 44: proto.MilpacService.SearchByPosition:output_type -> proto.LiteRoster
	18, // 45: proto.MilpacService.GetS1UniformsRoster:output_type -> proto.S1UniformsRoster
	22, // 46: proto.MilpacService.GetAllRanks:output_type -> proto.RanksResponse
	23, // 47: proto.MilpacService.GetPositionGroups:output_type -> proto.PositionGroupsResponse
	27, // 48: proto.MilpacService.GetAwol:output_type -> proto.AwolResponse
	8,  // 49: proto.MilpacService.GetGamertagProfile:output_type -> proto.Profile
	39, // [39:50] is the sub-list for method output_type
	28, // [28:39] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_milpacs_proto_init() }
func file_milpacs_proto_init() {
	if File_milpacs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_milpacs_proto_rawDesc), len(file_milpacs_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_milpacs_proto_goTypes,
		DependencyIndexes: file_milpacs_proto_depIdxs,
		EnumInfos:         file_milpacs_proto_enumTypes,
		MessageInfos:      file_milpacs_proto_msgTypes,
	}.Build()
	File_milpacs_proto = out.File
	file_milpacs_proto_goTypes = nil
	file_milpacs_proto_depIdxs = nil
}
