//
//  Copyright (C) 2026 7Cav.us
//  This file is part of 7Cav-API <https://github.com/7cav/api>.
//
//  Licensed under the GNU General Public License v3 (see milpacs.proto for
//  the full notice).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tickets.proto

package proto

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ticket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity
	TicketId  uint32 `protobuf:"varint,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	TicketRef string `protobuf:"bytes,2,opt,name=ticket_ref,json=ticketRef,proto3" json:"ticket_ref,omitempty"`
	Title     string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// Category
	CategoryId          uint32   `protobuf:"varint,10,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryTitle       string   `protobuf:"bytes,11,opt,name=category_title,json=categoryTitle,proto3" json:"category_title,omitempty"`
	CategoryAncestorIds []uint32 `protobuf:"varint,12,rep,packed,name=category_ancestor_ids,json=categoryAncestorIds,proto3" json:"category_ancestor_ids,omitempty"`
	// State / workflow
	TicketState     string `protobuf:"bytes,20,opt,name=ticket_state,json=ticketState,proto3" json:"ticket_state,omitempty"`
	StatusId        uint32 `protobuf:"varint,21,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	StatusName      string `protobuf:"bytes,22,opt,name=status_name,json=statusName,proto3" json:"status_name,omitempty"`
	PriorityId      uint32 `protobuf:"varint,23,opt,name=priority_id,json=priorityId,proto3" json:"priority_id,omitempty"`
	PriorityName    string `protobuf:"bytes,24,opt,name=priority_name,json=priorityName,proto3" json:"priority_name,omitempty"`
	PrefixId        uint32 `protobuf:"varint,25,opt,name=prefix_id,json=prefixId,proto3" json:"prefix_id,omitempty"`
	PrefixName      string `protobuf:"bytes,26,opt,name=prefix_name,json=prefixName,proto3" json:"prefix_name,omitempty"`
	DiscussionState string `protobuf:"bytes,27,opt,name=discussion_state,json=discussionState,proto3" json:"discussion_state,omitempty"`
	TicketLocked    bool   `protobuf:"varint,28,opt,name=ticket_locked,json=ticketLocked,proto3" json:"ticket_locked,omitempty"`
	// People
	StarterUserId    uint32               `protobuf:"varint,30,opt,name=starter_user_id,json=starterUserId,proto3" json:"starter_user_id,omitempty"`
	StarterUsername  string               `protobuf:"bytes,31,opt,name=starter_username,json=starterUsername,proto3" json:"starter_username,omitempty"`
	AssignedUserId   uint32               `protobuf:"varint,32,opt,name=assigned_user_id,json=assignedUserId,proto3" json:"assigned_user_id,omitempty"`
	AssignedUsername string               `protobuf:"bytes,33,opt,name=assigned_username,json=assignedUsername,proto3" json:"assigned_username,omitempty"`
	Participants     []*TicketParticipant `protobuf:"bytes,34,rep,name=participants,proto3" json:"participants,omitempty"`
	// Activity
	StartDate           uint32 `protobuf:"varint,40,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	LastMessageDate     uint32 `protobuf:"varint,41,opt,name=last_message_date,json=lastMessageDate,proto3" json:"last_message_date,omitempty"`
	LastMessageUserId   uint32 `protobuf:"varint,42,opt,name=last_message_user_id,json=lastMessageUserId,proto3" json:"last_message_user_id,omitempty"`
	LastMessageUsername string `protobuf:"bytes,43,opt,name=last_message_username,json=lastMessageUsername,proto3" json:"last_message_username,omitempty"`
	LastModifiedDate    uint32 `protobuf:"varint,44,opt,name=last_modified_date,json=lastModifiedDate,proto3" json:"last_modified_date,omitempty"`
	ReplyCount          uint32 `protobuf:"varint,45,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"`
	// Total messages in this ticket including the starter post. Equivalent
	// to reply_count + 1.
	TotalMessageCount uint32 `protobuf:"varint,46,opt,name=total_message_count,json=totalMessageCount,proto3" json:"total_message_count,omitempty"`
	// Data
	CustomFields map[string]string `protobuf:"bytes,50,rep,name=custom_fields,json=customFields,proto3" json:"custom_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Convenience
	ForumUrl      string `protobuf:"bytes,60,opt,name=forum_url,json=forumUrl,proto3" json:"forum_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	mi := &file_tickets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

func (x *Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticket.ProtoReflect.Descriptor instead.
func (*Ticket) Descriptor() ([]byte, []int) {
	return file_tickets_proto_rawDescGZIP(), []int{0}
}

func (x *Ticket) GetTicketId() uint32 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *Ticket) GetTicketRef() string {
	if x != nil {
		return x.TicketRef
	}
	return ""
}

func (x *Ticket) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Ticket) GetCategoryId() uint32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Ticket) GetCategoryTitle() string {
	if x != nil {
		return x.CategoryTitle
	}
	return ""
}

func (x *Ticket) GetCategoryAncestorIds() []uint32 {
	if x != nil {
		return x.CategoryAncestorIds
	}
	return nil
}

func (x *Ticket) GetTicketState() string {
	if x != nil {
		return x.TicketState
	}
	return ""
}

func (x *Ticket) GetStatusId() uint32 {
	if x != nil {
		return x.StatusId
	}
	return 0
}

func (x *Ticket) GetStatusName() string {
	if x != nil {
		return x.StatusName
	}
	return ""
}

func (x *Ticket) GetPriorityId() uint32 {
	if x != nil {
		return x.PriorityId
	}
	return 0
}

func (x *Ticket) GetPriorityName() string {
	if x != nil {
		return x.PriorityName
	}
	return ""
}

func (x *Ticket) GetPrefixId() uint32 {
	if x != nil {
		return x.PrefixId
	}
	return 0
}

func (x *Ticket) GetPrefixName() string {
	if x != nil {
		return x.PrefixName
	}
	return ""
}

func (x *Ticket) GetDiscussionState() string {
	if x != nil {
		return x.DiscussionState
	}
	return ""
}

func (x *Ticket) GetTicketLocked() bool {
	if x != nil {
		return x.TicketLocked
	}
	return false
}

func (x *Ticket) GetStarterUserId() uint32 {
	if x != nil {
		return x.StarterUserId
	}
	return 0
}

func (x *Ticket) GetStarterUsername() string {
	if x != nil {
		return x.StarterUsername
	}
	return ""
}

func (x *Ticket) GetAssignedUserId() uint32 {
	if x != nil {
		return x.AssignedUserId
	}
	return 0
}

func (x *Ticket) GetAssignedUsername() string {
	if x != nil {
		return x.AssignedUsername
	}
	return ""
}

func (x *Ticket) GetParticipants() []*TicketParticipant {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *Ticket) GetStartDate() uint32 {
	if x != nil {
		return x.StartDate
	}
	return 0
}

func (x *Ticket) GetLastMessageDate() uint32 {
	if x != nil {
		return x.LastMessageDate
	}
	return 0
}

func (x *Ticket) GetLastMessageUserId() uint32 {
	if x != nil {
		return x.LastMessageUserId
	}
	return 0
}

func (x *Ticket) GetLastMessageUsername() string {
	if x != nil {
		return x.LastMessageUsername
	}
	return ""
}

func (x *Ticket) GetLastModifiedDate() uint32 {
	if x != nil {
		return x.LastModifiedDate
	}
	return 0
}

func (x *Ticket) GetReplyCount() uint32 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

func (x *Ticket) GetTotalMessageCount() uint32 {
	if x != nil {
		return x.TotalMessageCount
	}
	return 0
}

func (x *Ticket) GetCustomFields() map[string]string {
	if x != nil {
		return x.CustomFields
	}
	return nil
}

func (x *Ticket) GetForumUrl() string {
	if x != nil {
		return x.ForumUrl
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     uint32                 `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	TicketId      uint32                 `protobuf:"varint,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	MessageDate   uint32                 `protobuf:"varint,5,opt,name=message_date,json=messageDate,proto3" json:"message_date,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	MessageState  string                 `protobuf:"bytes,7,opt,name=message_state,json=messageState,proto3" json:"message_state,omitempty"`
	Position      uint32                 `protobuf:"varint,8,opt,name=position,proto3" json:"position,omitempty"`
	AttachCount   uint32                 `protobuf:"varint,9,opt,name=attach_count,json=attachCount,proto3" json:"attach_count,omitempty"`
	LastEditDate  uint32                 `protobuf:"varint,10,opt,name=last_edit_date,json=lastEditDate,proto3" json:"last_edit_date,omitempty"`
	EditCount     uint32                 `protobuf:"varint,11,opt,name=edit_count,json=editCount,proto3" json:"edit_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_tickets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_tickets_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetMessageId() uint32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *Message) GetTicketId() uint32 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *Message) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Message) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Message) GetMessageDate() uint32 {
	if x != nil {
		return x.MessageDate
	}
	return 0
}

func (x *Message) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Message) GetMessageState() string {
	if x != nil {
		return x.MessageState
	}
	return ""
}

func (x *Message) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Message) GetAttachCount() uint32 {
	if x != nil {
		return x.AttachCount
	}
	return 0
}

func (x *Message) GetLastEditDate() uint32 {
	if x != nil {
		return x.LastEditDate
	}
	return 0
}

func (x *Message) GetEditCount() uint32 {
	if x != nil {
		return x.EditCount
	}
	return 0
}

type Category struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CategoryId       uint32                 `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ParentCategoryId uint32                 `protobuf:"varint,4,opt,name=parent_category_id,json=parentCategoryId,proto3" json:"parent_category_id,omitempty"`
	Depth            uint32                 `protobuf:"varint,5,opt,name=depth,proto3" json:"depth,omitempty"`
	DisplayOrder     uint32                 `protobuf:"varint,6,opt,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`
	TicketCount      uint32                 `protobuf:"varint,7,opt,name=ticket_count,json=ticketCount,proto3" json:"ticket_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_tickets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_tickets_proto_rawDescGZIP(), []int{2}
}

func (x *Category) GetCategoryId() uint32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Category) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Category) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Category) GetParentCategoryId() uint32 {
	if x != nil {
		return x.ParentCategoryId
	}
	return 0
}

func (x *Category) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *Category) GetDisplayOrder() uint32 {
	if x != nil {
		return x.DisplayOrder
	}
	return 0
}

func (x *Category) GetTicketCount() uint32 {
	if x != nil {
		return x.TicketCount
	}
	return 0
}

type TicketParticipant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LastReadDate  uint32                 `protobuf:"varint,2,opt,name=last_read_date,json=lastReadDate,proto3" json:"last_read_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketParticipant) Reset() {
	*x = TicketParticipant{}
	mi := &file_tickets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketParticipant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketParticipant) ProtoMessage() {}

func (x *TicketParticipant) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketParticipant.ProtoReflect.Descriptor instead.
func (*TicketParticipant) Descriptor() ([]byte, []int) {
	return file_tickets_proto_rawDescGZIP(), []int{3}
}

func (x *TicketParticipant) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TicketParticipant) GetLastReadDate() uint32 {
	if x != nil {
		return x.LastReadDate
	}
	return 0
}

type ListTicketsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Multi-select by repeating the param: ?category_id=1&category_id=5.
	// Comma-separated form (?category_id=1,5) is NOT supported.
	CategoryId           []uint32 `protobuf:"varint,1,rep,packed,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	ExcludeSubcategories bool     `protobuf:"varint,2,opt,name=exclude_subcategories,json=excludeSubcategories,proto3" json:"exclude_subcategories,omitempty"`
	// Multi-select by repeating the param: ?ticket_state=open&ticket_state=resolved.
	// Comma-separated form is NOT supported.
	TicketState []string `protobuf:"bytes,3,rep,name=ticket_state,json=ticketState,proto3" json:"ticket_state,omitempty"`
	// Multi-select by repeating the param: ?status_id=1&status_id=3.
	// Comma-separated form is NOT supported.
	StatusId []uint32 `protobuf:"varint,4,rep,packed,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	// Multi-select by repeating the param: ?prefix_id=1&prefix_id=2.
	// Comma-separated form is NOT supported.
	PrefixId []uint32 `protobuf:"varint,5,rep,packed,name=prefix_id,json=prefixId,proto3" json:"prefix_id,omitempty"`
	// Multi-select by repeating the param: ?assigned_user_id=1&assigned_user_id=2.
	// Comma-separated form is NOT supported.
	AssignedUserId []uint32 `protobuf:"varint,6,rep,packed,name=assigned_user_id,json=assignedUserId,proto3" json:"assigned_user_id,omitempty"`
	// Multi-select by repeating the param: ?starter_user_id=1&starter_user_id=2.
	// Comma-separated form is NOT supported.
	StarterUserId []uint32 `protobuf:"varint,7,rep,packed,name=starter_user_id,json=starterUserId,proto3" json:"starter_user_id,omitempty"`
	ModifiedSince uint32   `protobuf:"varint,8,opt,name=modified_since,json=modifiedSince,proto3" json:"modified_since,omitempty"`
	IncludeHidden bool     `protobuf:"varint,9,opt,name=include_hidden,json=includeHidden,proto3" json:"include_hidden,omitempty"`
	PerPage       uint32   `protobuf:"varint,50,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	AfterCursor   string   `protobuf:"bytes,51,opt,name=after_cursor,json=afterCursor,proto3" json:"after_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketsRequest) Reset() {
	*x = ListTicketsRequest{}
	mi := &file_tickets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketsRequest) ProtoMessage() {}

func (x *ListTicketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketsRequest.ProtoReflect.Descriptor instead.
func (*ListTicketsRequest) Descriptor() ([]byte, []int) {
	return file_tickets_proto_rawDescGZIP(), []int{4}
}

func (x *ListTicketsRequest) GetCategoryId() []uint32 {
	if x != nil {
		return x.CategoryId
	}
	return nil
}

func (x *ListTicketsRequest) GetExcludeSubcategories() bool {
	if x != nil {
		return x.ExcludeSubcategories
	}
	return false
}

func (x *ListTicketsRequest) GetTicketState() []string {
	if x != nil {
		return x.TicketState
	}
	return nil
}

func (x *ListTicketsRequest) GetStatusId() []uint32 {
	if x != nil {
		return x.StatusId
	}
	return nil
}

func (x *ListTicketsRequest) GetPrefixId() []uint32 {
	if x != nil {
		return x.PrefixId
	}
	return nil
}

func (x *ListTicketsRequest) GetAssignedUserId() []uint32 {
	if x != nil {
		return x.AssignedUserId
	}
	return nil
}

func (x *ListTicketsRequest) GetStarterUserId() []uint32 {
	if x != nil {
		return x.StarterUserId
	}
	return nil
}

func (x *ListTicketsRequest) GetModifiedSince() uint32 {
	if x != nil {
		return x.ModifiedSince
	}
	return 0
}

func (x *ListTicketsRequest) GetIncludeHidden() bool {
	if x != nil {
		return x.IncludeHidden
	}
	return false
}

func (x *ListTicketsRequest) GetPerPage() uint32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *ListTicketsRequest) GetAfterCursor() string {
	if x != nil {
		return x.AfterCursor
	}
	return ""
}

type ListTicketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickets       []*Ticket              `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketsResponse) Reset() {
	*x = ListTicketsResponse{}
	mi := &file_tickets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketsResponse) ProtoMessage() {}

func (x *ListTicketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketsResponse.ProtoReflect.Descriptor instead.
func (*ListTicketsResponse) Descriptor() ([]byte, []int) {
	return file_tickets_proto_rawDescGZIP(), []int{5}
}

func (x *ListTicketsResponse) GetTickets() []*Ticket {
	if x != nil {
		return x.Tickets
	}
	return nil
}

func (x *ListTicketsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListTicketsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      uint32                 `protobuf:"varint,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketRequest) Reset() {
	*x = GetTicketRequest{}
	mi := &file_tickets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketRequest) ProtoMessage() {}

func (x *GetTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketRequest.ProtoReflect.Descriptor instead.
func (*GetTicketRequest) Descriptor() ([]byte, []int) {
	return file_tickets_proto_rawDescGZIP(), []int{6}
}

func (x *GetTicketRequest) GetTicketId() uint32 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

type GetTicketByRefRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketRef     string                 `protobuf:"bytes,1,opt,name=ticket_ref,json=ticketRef,proto3" json:"ticket_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketByRefRequest) Reset() {
	*x = GetTicketByRefRequest{}
	mi := &file_tickets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketByRefRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketByRefRequest) ProtoMessage() {}

func (x *GetTicketByRefRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketByRefRequest.ProtoReflect.Descriptor instead.
func (*GetTicketByRefRequest) Descriptor() ([]byte, []int) {
	return file_tickets_proto_rawDescGZIP(), []int{7}
}

func (x *GetTicketByRefRequest) GetTicketRef() string {
	if x != nil {
		return x.TicketRef
	}
	return ""
}

type GetTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        *Ticket                `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	FirstMessages []*Message             `protobuf:"bytes,2,rep,name=first_messages,json=firstMessages,proto3" json:"first_messages,omitempty"`
	// DEPRECATED: use ticket.total_message_count. Removal target: v2.3.0.
	//
	// Deprecated: Marked as deprecated in tickets.proto.
	TotalMessageCount uint32 `protobuf:"varint,3,opt,name=total_message_count,json=totalMessageCount,proto3" json:"total_message_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetTicketResponse) Reset() {
	*x = GetTicketResponse{}
	mi := &file_tickets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketResponse) ProtoMessage() {}

func (x *GetTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketResponse.ProtoReflect.Descriptor instead.
func (*GetTicketResponse) Descriptor() ([]byte, []int) {
	return file_tickets_proto_rawDescGZIP(), []int{8}
}

func (x *GetTicketResponse) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

func (x *GetTicketResponse) GetFirstMessages() []*Message {
	if x != nil {
		return x.FirstMessages
	}
	return nil
}

// Deprecated: Marked as deprecated in tickets.proto.
func (x *GetTicketResponse) GetTotalMessageCount() uint32 {
	if x != nil {
		return x.TotalMessageCount
	}
	return 0
}

type ListTicketMessagesRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TicketId uint32                 `protobuf:"varint,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	PerPage  uint32                 `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	// Opaque cursor; empty string = first page. Round-trip the next_cursor
	// from the previous response. Pagination is by message position
	// ascending.
	AfterCursor   string `protobuf:"bytes,3,opt,name=after_cursor,json=afterCursor,proto3" json:"after_cursor,omitempty"`
	IncludeHidden bool   `protobuf:"varint,4,opt,name=include_hidden,json=includeHidden,proto3" json:"include_hidden,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketMessagesRequest) Reset() {
	*x = ListTicketMessagesRequest{}
	mi := &file_tickets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketMessagesRequest) ProtoMessage() {}

func (x *ListTicketMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListTicketMessagesRequest) Descriptor() ([]byte, []int) {
	return file_tickets_proto_rawDescGZIP(), []int{9}
}

func (x *ListTicketMessagesRequest) GetTicketId() uint32 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *ListTicketMessagesRequest) GetPerPage() uint32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *ListTicketMessagesRequest) GetAfterCursor() string {
	if x != nil {
		return x.AfterCursor
	}
	return ""
}

func (x *ListTicketMessagesRequest) GetIncludeHidden() bool {
	if x != nil {
		return x.IncludeHidden
	}
	return false
}

type ListTicketMessagesResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Messages []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	// Opaque cursor; empty when has_more=false.
	NextCursor    string `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketMessagesResponse) Reset() {
	*x = ListTicketMessagesResponse{}
	mi := &file_tickets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketMessagesResponse) ProtoMessage() {}

func (x *ListTicketMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListTicketMessagesResponse) Descriptor() ([]byte, []int) {
	return file_tickets_proto_rawDescGZIP(), []int{10}
}

func (x *ListTicketMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListTicketMessagesResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListTicketMessagesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_tickets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_tickets_proto_rawDescGZIP(), []int{11}
}

func (x *ListCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

var File_tickets_proto protoreflect.FileDescriptor

const file_tickets_proto_rawDesc = "" +
	"\n" +
	"\rtickets.proto\x12\x05proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xc6\t\n" +
	"\x06Ticket\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\rR\bticketId\x12\x1d\n" +
	"\n" +
	"ticket_ref\x18\x02 \x01(\tR\tticketRef\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1f\n" +
	"\vcategory_id\x18\n" +
	" \x01(\rR\n" +
	"categoryId\x12%\n" +
	"\x0ecategory_title\x18\v \x01(\tR\rcategoryTitle\x122\n" +
	"\x15category_ancestor_ids\x18\f \x03(\rR\x13categoryAncestorIds\x12!\n" +
	"\fticket_state\x18\x14 \x01(\tR\vticketState\x12\x1b\n" +
	"\tstatus_id\x18\x15 \x01(\rR\bstatusId\x12\x1f\n" +
	"\vstatus_name\x18\x16 \x01(\tR\n" +
	"statusName\x12\x1f\n" +
	"\vpriority_id\x18\x17 \x01(\rR\n" +
	"priorityId\x12#\n" +
	"\rpriority_name\x18\x18 \x01(\tR\fpriorityName\x12\x1b\n" +
	"\tprefix_id\x18\x19 \x01(\rR\bprefixId\x12\x1f\n" +
	"\vprefix_name\x18\x1a \x01(\tR\n" +
	"prefixName\x12)\n" +
	"\x10discussion_state\x18\x1b \x01(\tR\x0fdiscussionState\x12#\n" +
	"\rticket_locked\x18\x1c \x01(\bR\fticketLocked\x12&\n" +
	"\x0fstarter_user_id\x18\x1e \x01(\rR\rstarterUserId\x12)\n" +
	"\x10starter_username\x18\x1f \x01(\tR\x0fstarterUsername\x12(\n" +
	"\x10assigned_user_id\x18  \x01(\rR\x0eassignedUserId\x12+\n" +
	"\x11assigned_username\x18! \x01(\tR\x10assignedUsername\x12<\n" +
	"\fparticipants\x18\" \x03(\v2\x18.proto.TicketParticipantR\fparticipants\x12\x1d\n" +
	"\n" +
	"start_date\x18( \x01(\rR\tstartDate\x12*\n" +
	"\x11last_message_date\x18) \x01(\rR\x0flastMessageDate\x12/\n" +
	"\x14last_message_user_id\x18* \x01(\rR\x11lastMessageUserId\x122\n" +
	"\x15last_message_username\x18+ \x01(\tR\x13lastMessageUsername\x12,\n" +
	"\x12last_modified_date\x18, \x01(\rR\x10lastModifiedDate\x12\x1f\n" +
	"\vreply_count\x18- \x01(\rR\n" +
	"replyCount\x12.\n" +
	"\x13total_message_count\x18. \x01(\rR\x11totalMessageCount\x12D\n" +
	"\rcustom_fields\x182 \x03(\v2\x1f.proto.Ticket.CustomFieldsEntryR\fcustomFields\x12\x1b\n" +
	"\tforum_url\x18< \x01(\tR\bforumUrl\x1a?\n" +
	"\x11CustomFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe0\x02\n" +
	"\aMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\rR\tmessageId\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\rR\bticketId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12!\n" +
	"\fmessage_date\x18\x05 \x01(\rR\vmessageDate\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12#\n" +
	"\rmessage_state\x18\a \x01(\tR\fmessageState\x12\x1a\n" +
	"\bposition\x18\b \x01(\rR\bposition\x12!\n" +
	"\fattach_count\x18\t \x01(\rR\vattachCount\x12$\n" +
	"\x0elast_edit_date\x18\n" +
	" \x01(\rR\flastEditDate\x12\x1d\n" +
	"\n" +
	"edit_count\x18\v \x01(\rR\teditCount\"\xef\x01\n" +
	"\bCategory\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\rR\n" +
	"categoryId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12,\n" +
	"\x12parent_category_id\x18\x04 \x01(\rR\x10parentCategoryId\x12\x14\n" +
	"\x05depth\x18\x05 \x01(\rR\x05depth\x12#\n" +
	"\rdisplay_order\x18\x06 \x01(\rR\fdisplayOrder\x12!\n" +
	"\fticket_count\x18\a \x01(\rR\vticketCount\"R\n" +
	"\x11TicketParticipant\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12$\n" +
	"\x0elast_read_date\x18\x02 \x01(\rR\flastReadDate\"\xa5\x03\n" +
	"\x12ListTicketsRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x03(\rR\n" +
	"categoryId\x123\n" +
	"\x15exclude_subcategories\x18\x02 \x01(\bR\x14excludeSubcategories\x12!\n" +
	"\fticket_state\x18\x03 \x03(\tR\vticketState\x12\x1b\n" +
	"\tstatus_id\x18\x04 \x03(\rR\bstatusId\x12\x1b\n" +
	"\tprefix_id\x18\x05 \x03(\rR\bprefixId\x12(\n" +
	"\x10assigned_user_id\x18\x06 \x03(\rR\x0eassignedUserId\x12&\n" +
	"\x0fstarter_user_id\x18\a \x03(\rR\rstarterUserId\x12%\n" +
	"\x0emodified_since\x18\b \x01(\rR\rmodifiedSince\x12%\n" +
	"\x0einclude_hidden\x18\t \x01(\bR\rincludeHidden\x12\x19\n" +
	"\bper_page\x182 \x01(\rR\aperPage\x12!\n" +
	"\fafter_cursor\x183 \x01(\tR\vafterCursor\"z\n" +
	"\x13ListTicketsResponse\x12'\n" +
	"\atickets\x18\x01 \x03(\v2\r.proto.TicketR\atickets\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"/\n" +
	"\x10GetTicketRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\rR\bticketId\"6\n" +
	"\x15GetTicketByRefRequest\x12\x1d\n" +
	"\n" +
	"ticket_ref\x18\x01 \x01(\tR\tticketRef\"\xa5\x01\n" +
	"\x11GetTicketResponse\x12%\n" +
	"\x06ticket\x18\x01 \x01(\v2\r.proto.TicketR\x06ticket\x125\n" +
	"\x0efirst_messages\x18\x02 \x03(\v2\x0e.proto.MessageR\rfirstMessages\x122\n" +
	"\x13total_message_count\x18\x03 \x01(\rB\x02\x18\x01R\x11totalMessageCount\"\x9d\x01\n" +
	"\x19ListTicketMessagesRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\rR\bticketId\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\rR\aperPage\x12!\n" +
	"\fafter_cursor\x18\x03 \x01(\tR\vafterCursor\x12%\n" +
	"\x0einclude_hidden\x18\x04 \x01(\bR\rincludeHidden\"\x84\x01\n" +
	"\x1aListTicketMessagesResponse\x12*\n" +
	"\bmessages\x18\x01 \x03(\v2\x0e.proto.MessageR\bmessages\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"I\n" +
	"\x16ListCategoriesResponse\x12/\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x0f.proto.CategoryR\n" +
	"categories2\xb7\v\n" +
	"\x0eTicketsService\x12\x9d\x02\n" +
	"\vListTickets\x12\x19.proto.ListTicketsRequest\x1a\x1a.proto.ListTicketsResponse\"\xd6\x01\x92A\xbb\x01\n" +
	"\aTickets\x12\fList tickets\x1a\xa1\x01List tickets matching optional filters (category, state, status, prefix, assignee, starter, modified_since). Cursor-paginated, sorted by last_modified_date DESC.\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/tickets\x12\xbf\x02\n" +
	"\tGetTicket\x12\x17.proto.GetTicketRequest\x1a\x18.proto.GetTicketResponse\"\xfe\x01\x92A\xd7\x01\n" +
	"\aTickets\x12\x1aGet a ticket by numeric ID\x1a\xaf\x01Fetch a single ticket by its integer ticket_id. Response includes the first 10 messages (oldest first) and the total message count; use ListTicketMessages for the full thread.\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/tickets/{ticket_id}\x12\x8e\x02\n" +
	"\x0eGetTicketByRef\x12\x1c.proto.GetTicketByRefRequest\x1a\x18.proto.GetTicketResponse\"\xc3\x01\x92A\x97\x01\n" +
	"\aTickets\x12\x18Get a ticket by ref slug\x1arFetch a single ticket by its user-facing alphanumeric reference (e.g. MF1UI9HE). Same response shape as GetTicket.\x82\xd3\xe4\x93\x02\"\x12 /api/v1/tickets/ref/{ticket_ref}\x12\xac\x02\n" +
	"\x12ListTicketMessages\x12 .proto.ListTicketMessagesRequest\x1a!.proto.ListTicketMessagesResponse\"\xd0\x01\x92A\xa0\x01\n" +
	"\aTickets\x12\x19List messages on a ticket\x1azPaginated thread of messages for a single ticket, ordered by position ascending. Cursor uses position (unique per ticket).\x82\xd3\xe4\x93\x02&\x12$/api/v1/tickets/{ticket_id}/messages\x12\x82\x02\n" +
	"\x0eListCategories\x12\x16.google.protobuf.Empty\x1a\x1d.proto.ListCategoriesResponse\"\xb8\x01\x92A\x92\x01\n" +
	"\aTickets\x12\x16List ticket categories\x1aoReturns the full nixfifty category tree (24 entries). Reference data for the category_id filter on ListTickets.\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/tickets/categoriesB\x82\x02\x92A\xe3\x01\x12Q\n" +
	"\x107Cav Tickets API\x128Read-only access to 7Cav forum tickets (nixfifty addon).2\x03dev*\x01\x022\x10application/json:\x10application/jsonZY\n" +
	"W\n" +
	"\x06bearer\x12M\b\x02\x128Authentication token, prefixed by Bearer: Bearer <token>\x1a\rAuthorization \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00Z\x19github.com/7cav/api/protob\x06proto3"

var (
	file_tickets_proto_rawDescOnce sync.Once
	file_tickets_proto_rawDescData []byte
)

func file_tickets_proto_rawDescGZIP() []byte {
	file_tickets_proto_rawDescOnce.Do(func() {
		file_tickets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tickets_proto_rawDesc), len(file_tickets_proto_rawDesc)))
	})
	return file_tickets_proto_rawDescData
}

var file_tickets_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_tickets_proto_goTypes = []any{
	(*Ticket)(nil),                     // 0: proto.Ticket
	(*Message)(nil),                    // 1: proto.Message
	(*Category)(nil),                   // 2: proto.Category
	(*TicketParticipant)(nil),          // 3: proto.TicketParticipant
	(*ListTicketsRequest)(nil),         // 4: proto.ListTicketsRequest
	(*ListTicketsResponse)(nil),        // 5: proto.ListTicketsResponse
	(*GetTicketRequest)(nil),           // 6: proto.GetTicketRequest
	(*GetTicketByRefRequest)(nil),      // 7: proto.GetTicketByRefRequest
	(*GetTicketResponse)(nil),          // 8: proto.GetTicketResponse
	(*ListTicketMessagesRequest)(nil),  // 9: proto.ListTicketMessagesRequest
	(*ListTicketMessagesResponse)(nil), // 10: proto.ListTicketMessagesResponse
	(*ListCategoriesResponse)(nil),     // 11: proto.ListCategoriesResponse
	nil,                                // 12: proto.Ticket.CustomFieldsEntry
	(*emptypb.Empty)(nil),              // 13: google.protobuf.Empty
}
var file_tickets_proto_depIdxs = []int32{
	3,  // 0: proto.Ticket.participants:type_name -> proto.TicketParticipant
	12, // 1: proto.Ticket.custom_fields:type_name -> proto.Ticket.CustomFieldsEntry
	0,  // 2: proto.ListTicketsResponse.tickets:type_name -> proto.Ticket
	0,  // 3: proto.GetTicketResponse.ticket:type_name -> proto.Ticket
	1,  // 4: proto.GetTicketResponse.first_messages:type_name -> proto.Message
	1,  // 5: proto.ListTicketMessagesResponse.messages:type_name -> proto.Message
	2,  // 6: proto.ListCategoriesResponse.categories:type_name -> proto.Category
	4,  // 7: proto.TicketsService.ListTickets:input_type -> proto.ListTicketsRequest
	6,  // 8: proto.TicketsService.GetTicket:input_type -> proto.GetTicketRequest
	7,  // 9: proto.TicketsService.GetTicketByRef:input_type -> proto.GetTicketByRefRequest
	9,  // 10: proto.TicketsService.ListTicketMessages:input_type -> proto.ListTicketMessagesRequest
	13, // 11: proto.TicketsService.ListCategories:input_type -> google.protobuf.Empty
	5,  // 12: proto.TicketsService.ListTickets:output_type -> proto.ListTicketsResponse
	8,  // 13: proto.TicketsService.GetTicket:output_type -> proto.GetTicketResponse
	8,  // 14: proto.TicketsService.GetTicketByRef:output_type -> proto.GetTicketResponse
	10, // 15: proto.TicketsService.ListTicketMessages:output_type -> proto.ListTicketMessagesResponse
	11, // 16: proto.TicketsService.ListCategories:output_type -> proto.ListCategoriesResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_tickets_proto_init() }
func file_tickets_proto_init() {
	if File_tickets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tickets_proto_rawDesc), len(file_tickets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tickets_proto_goTypes,
		DependencyIndexes: file_tickets_proto_depIdxs,
		MessageInfos:      file_tickets_proto_msgTypes,
	}.Build()
	File_tickets_proto = out.File
	file_tickets_proto_goTypes = nil
	file_tickets_proto_depIdxs = nil
}
