name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Install tools
      run: make install
    - name: Regenerate files
      run: make generate
    - name: Tidy
      run: go mod tidy
    - name: Build
      run: go build -v ./...
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Install tools
      run: make install
    - name: Install buf
      run: |
        curl -sSL https://github.com/bufbuild/buf/releases/download/v1.20.0/buf-Linux-x86_64 -o /usr/local/bin/buf
        chmod +x /usr/local/bin/buf
    - name: Lint
      run: make lint
